use super::*;

// `assura audit [path]` -- scan and verify a Rust project
// ---------------------------------------------------------------------------

pub(crate) fn run_audit(opts: AuditOptions<'_>) {
    let AuditOptions {
        path,
        depth,
        format,
        focus,
        max_functions,
        timeout_ms: _timeout_ms,
        unsafe_only,
    } = opts;
    use assura_codegen::type_map::rust_type_to_assura;

    // Phase 1: Discover Rust source files
    let root = Path::new(path);
    let cargo_toml = root.join("Cargo.toml");
    if !cargo_toml.exists() {
        eprintln!("Error: no Cargo.toml found at {}", root.display());
        eprintln!("Run `assura audit` from a Cargo workspace root.");
        process::exit(2);
    }

    // Discover src directories: support workspaces and single crates
    let src_dirs = discover_workspace_src_dirs(root);
    if src_dirs.is_empty() {
        eprintln!("Error: no src/ directories found at {}", root.display());
        process::exit(2);
    }

    let mut rs_files = Vec::new();
    for src_dir in &src_dirs {
        rs_files.extend(discover_rs_files(src_dir));
    }
    rs_files.sort();
    rs_files.dedup();

    if rs_files.is_empty() {
        eprintln!("No .rs files found in scanned directories");
        process::exit(1);
    }

    // Phase 2: Extract all function signatures
    let mut all_sigs: Vec<(String, RustFnSig)> = Vec::new();
    for rs_file in &rs_files {
        let rel_path = rs_file
            .strip_prefix(root)
            .unwrap_or(rs_file.as_path())
            .to_string_lossy()
            .to_string();

        let source = match fs::read_to_string(rs_file) {
            Ok(s) => s,
            Err(_) => continue,
        };

        let sigs = extract_rust_fn_signatures(&source);
        for sig in sigs {
            if !sig.is_pub {
                continue;
            }
            if unsafe_only && !source.contains("unsafe") {
                continue;
            }
            if let Some(pattern) = focus {
                let qname = format!("{}::{}", rel_path, sig.name);
                if !qname.contains(pattern) && !sig.name.contains(pattern) {
                    continue;
                }
            }
            all_sigs.push((rel_path.clone(), sig));
        }
    }

    if let Some(max) = max_functions {
        all_sigs.truncate(max);
    }

    if all_sigs.is_empty() {
        eprintln!("No matching public functions found.");
        process::exit(1);
    }

    let is_json = format == "json";

    if !is_json {
        eprintln!(
            "Scanning {} ... found {} public functions in {} files",
            root.display(),
            all_sigs.len(),
            rs_files.len()
        );
    }

    // Phase 3: Generate skeleton contracts
    let mut assura_source = String::new();
    assura_source.push_str("// Auto-generated by: assura audit\n");
    assura_source.push_str("// Review and refine before relying on results.\n\n");

    for (file_path, sig) in &all_sigs {
        let module_path = derive_rust_module_path(file_path);

        let rust_path = format!("{module_path}::{}", sig.name);

        assura_source.push_str(&format!("bind \"{}\" as {} {{\n", rust_path, sig.name));

        if !sig.params.is_empty() {
            assura_source.push_str("    input(");
            let params: Vec<String> = sig
                .params
                .iter()
                .map(|(name, ty)| format!("{}: {}", name, rust_type_to_assura(ty)))
                .collect();
            assura_source.push_str(&params.join(", "));
            assura_source.push_str(")\n");
        }

        let assura_ret = rust_type_to_assura(&sig.return_type);
        if assura_ret != "Unit" {
            assura_source.push_str(&format!("    output(result: {assura_ret})\n"));
        }

        // Medium depth: add heuristic contracts
        if depth == "medium" || depth == "deep" {
            for (name, ty) in &sig.params {
                let aty = rust_type_to_assura(ty);
                // Index parameters: add bounds check
                if (aty == "Nat" || aty == "Int")
                    && (name.contains("index")
                        || name.contains("offset")
                        || name.contains("idx")
                        || name.contains("pos"))
                {
                    assura_source.push_str(&format!("    requires {name} >= 0\n"));
                }
                // Slice/list parameters: non-empty check
                if aty.starts_with("List") || aty == "Bytes" || aty == "String" {
                    assura_source.push_str(&format!("    requires length({name}) > 0\n"));
                }
            }
        }

        assura_source.push_str("}\n\n");
    }

    // Phase 4: Parse and verify the generated contracts
    if !is_json {
        eprintln!(
            "Generating contracts ... {} skeleton contracts",
            all_sigs.len()
        );
    }

    let (parsed, parse_errors) = assura_parser::parse(&assura_source);

    if !parse_errors.is_empty() && !is_json {
        eprintln!(
            "Warning: {} parse error(s) in generated contracts",
            parse_errors.len()
        );
    }

    let mut findings: Vec<AuditFinding> = Vec::new();
    let mut verified_count = 0u32;
    let mut error_count = 0u32;

    if let Some(file) = parsed {
        // Run resolve + type check + verify
        match assura_resolve::resolve(&file) {
            Ok(resolved) => match assura_types::type_check(&resolved) {
                Ok(typed) => {
                    if !is_json {
                        eprintln!("Verifying ...");
                    }
                    let audit_dir =
                        std::env::temp_dir().join(format!("assura-audit-{}", std::process::id()));
                    let _ = fs::create_dir_all(&audit_dir);
                    let audit_path = audit_dir.join("audit_generated.assura");
                    let _ = fs::write(&audit_path, &assura_source);
                    let loaded_ir = assura_smt::LoadedVerifyExtras::load(&audit_path, &typed);
                    let verify_cache = assura_smt::VerificationCache::new(&audit_dir);
                    let results = assura_smt::verify_parallel_with_solver(
                        &typed,
                        &verify_cache,
                        assura_smt::SolverChoice::Z3,
                        loaded_ir.extras().as_ref(),
                    );
                    let _ = fs::remove_dir_all(&audit_dir);
                    for r in &results {
                        match r {
                            assura_smt::VerificationResult::Verified { .. } => {
                                verified_count += 1;
                            }
                            assura_smt::VerificationResult::Counterexample {
                                clause_desc,
                                model,
                                ..
                            } => {
                                findings.push(AuditFinding {
                                    function: clause_desc.clone(),
                                    clause: "counterexample".to_string(),
                                    severity: "warning".to_string(),
                                    message: "Counterexample found".to_string(),
                                    counterexample: Some(model.clone()),
                                });
                            }
                            assura_smt::VerificationResult::Timeout { clause_desc } => {
                                findings.push(AuditFinding {
                                    function: clause_desc.clone(),
                                    clause: "timeout".to_string(),
                                    severity: "info".to_string(),
                                    message:
                                        "Z3 timed out (needs deeper contract or longer timeout)"
                                            .to_string(),
                                    counterexample: None,
                                });
                            }
                            assura_smt::VerificationResult::Unknown {
                                clause_desc,
                                reason,
                            } => {
                                findings.push(AuditFinding {
                                    function: clause_desc.clone(),
                                    clause: "unknown".to_string(),
                                    severity: "info".to_string(),
                                    message: format!("Z3 result unknown: {reason}"),
                                    counterexample: None,
                                });
                            }
                        }
                    }
                }
                Err(e) => {
                    if !is_json {
                        eprintln!("Type check error: {e:?}");
                    }
                    error_count += 1;
                }
            },
            Err(e) => {
                if !is_json {
                    eprintln!("Resolve error: {e:?}");
                }
                error_count += 1;
            }
        }
    }

    // Phase 5: Output results
    if is_json {
        let report = serde_json::json!({
            "functions_scanned": all_sigs.len(),
            "files_scanned": rs_files.len(),
            "verified": verified_count,
            "findings": findings.len(),
            "errors": error_count,
            "results": findings.iter().map(|f| serde_json::json!({
                "function": f.function,
                "clause": f.clause,
                "severity": f.severity,
                "message": f.message,
                "counterexample": f.counterexample,
            })).collect::<Vec<_>>(),
        });
        println!("{}", serde_json::to_string_pretty(&report).unwrap());
    } else {
        println!();
        println!(
            "AUDIT SUMMARY: {} functions, {} verified, {} findings, {} errors",
            all_sigs.len(),
            verified_count,
            findings.len(),
            error_count
        );

        if !findings.is_empty() {
            println!();
            println!("FINDINGS:");
            for f in &findings {
                let sev = match f.severity.as_str() {
                    "warning" => "WARNING",
                    "error" => "ERROR",
                    _ => "INFO",
                };
                println!("  [{sev}] {}  ({})", f.function, f.clause);
                println!("    {}", f.message);
                if let Some(cex) = &f.counterexample {
                    for line in cex.lines() {
                        println!("    | {line}");
                    }
                }
                println!();
            }
        }

        if findings.is_empty() && error_count == 0 {
            println!("  All verified contracts passed.");
        }
    }

    if !findings.is_empty() {
        process::exit(1);
    }
}

/// A finding from the audit.
pub(crate) struct AuditFinding {
    function: String,
    clause: String,
    severity: String,
    message: String,
    counterexample: Option<String>,
}

/// Recursively discover all .rs files under a directory.
/// Discover src/ directories from a Cargo project root.
///
/// If `Cargo.toml` has a `[workspace]` section with `members`, scan each
/// member's `src/` directory. Supports glob patterns like `crates/*`.
/// If it's a single-crate project, return `root/src/` if it exists.
pub(crate) fn discover_workspace_src_dirs(root: &Path) -> Vec<std::path::PathBuf> {
    let cargo_toml = root.join("Cargo.toml");
    let content = match fs::read_to_string(&cargo_toml) {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let mut src_dirs = Vec::new();

    // Check for workspace members
    let mut in_workspace = false;
    let mut in_members = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == "[workspace]" {
            in_workspace = true;
            continue;
        }
        if trimmed.starts_with('[') && trimmed != "[workspace]" {
            if in_workspace {
                in_workspace = false;
                in_members = false;
            }
            continue;
        }
        if in_workspace {
            if trimmed.starts_with("members") && trimmed.contains('[') {
                in_members = true;
            }
            if in_members {
                // Extract member paths from members = ["crates/*", "tools/*"]
                for segment in trimmed.split('"') {
                    let seg = segment.trim().trim_matches(',').trim();
                    if seg.is_empty()
                        || seg.starts_with('[')
                        || seg.starts_with(']')
                        || seg.contains('=')
                        || seg == "members"
                    {
                        continue;
                    }
                    // Expand glob patterns like crates/*
                    if seg.contains('*') {
                        let prefix = seg.trim_end_matches("/*").trim_end_matches("\\*");
                        let pattern_dir = root.join(prefix);
                        if let Ok(entries) = fs::read_dir(&pattern_dir) {
                            for entry in entries.flatten() {
                                let member_src = entry.path().join("src");
                                if member_src.is_dir() {
                                    src_dirs.push(member_src);
                                }
                            }
                        }
                    } else {
                        let member_src = root.join(seg).join("src");
                        if member_src.is_dir() {
                            src_dirs.push(member_src);
                        }
                    }
                }
                if trimmed.contains(']') {
                    in_members = false;
                }
            }
        }
    }

    // Fallback: single-crate project with src/
    if src_dirs.is_empty() {
        let src_dir = root.join("src");
        if src_dir.is_dir() {
            src_dirs.push(src_dir);
        }
    }

    src_dirs.sort();
    src_dirs
}

pub(crate) fn discover_rs_files(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(discover_rs_files(&path));
            } else if path.extension().is_some_and(|ext| ext == "rs") {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

// ---------------------------------------------------------------------------
