use super::*;

/// Helper: parse + resolve + type-check source text, then codegen.
fn codegen_ok(source: &str) -> GeneratedProject {
    let file = assura_parser::parse_unwrap(source);
    let resolved = assura_resolve::resolve(&file).expect("resolve failed");
    let typed = assura_types::type_check(&resolved).expect("type check failed");
    codegen(&typed)
}

#[test]
fn empty_file_generates_project() {
    let project = codegen_ok("");
    assert!(!project.cargo_toml.is_empty());
    assert_eq!(project.files.len(), 1);
    assert_eq!(project.files[0].0, "src/lib.rs");
    assert!(
        project.files[0]
            .1
            .contains("Generated by the Assura compiler")
    );
}

#[test]
fn struct_codegen() {
    let project = codegen_ok(
        r#"
type Point {
    x: Int
    y: Int
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("struct Point"), "should contain struct Point");
    assert!(lib.contains("i64"), "should map Int to i64");
}

#[test]
fn enum_codegen() {
    let project = codegen_ok(
        r#"
enum Color {
    Red,
    Green,
    Blue
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("enum Color"), "should contain enum Color");
    assert!(lib.contains("Red"), "should contain Red variant");
    assert!(lib.contains("Green"), "should contain Green variant");
    assert!(lib.contains("Blue"), "should contain Blue variant");
}

#[test]
fn enum_generates_display_impl() {
    let project = codegen_ok(
        r#"
enum Status {
    Active,
    Inactive,
    Pending
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("impl std::fmt::Display for Status"),
        "should generate Display impl: {lib}"
    );
    assert!(
        lib.contains("Status::Active => write!(f, \"Active\")"),
        "should have Active display arm: {lib}"
    );
}

#[test]
fn contract_generates_module() {
    let project = codegen_ok(
        r#"
contract SafeDivision {
    requires { true }
    ensures  { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("contract_safedivision"),
        "should contain contract module"
    );
}

#[test]
fn fn_def_codegen() {
    // Note: the current parser stores fn clauses in return_ty as raw
    // tokens rather than structured Clause objects. So fn codegen
    // generates the return type string including clause keywords.
    // The codegen still generates a valid function stub.
    let project = codegen_ok(
        r#"
fn helper(n: Int) -> Int {
    requires { n >= 0 }
    ensures  { result >= 0 }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("fn helper"), "should contain fn helper");
}

#[test]
fn contract_generates_debug_assert() {
    let project = codegen_ok(
        r#"
contract Positive {
    requires { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("debug_assert!"),
        "contract requires should generate debug_assert"
    );
}

#[test]
fn project_name_used_in_cargo_toml() {
    let project = codegen_ok(
        r#"
project my_cool_project {
    profile: [core]
}

contract Foo {
    requires { true }
}
"#,
    );
    assert!(
        project.cargo_toml.contains("my_cool_project"),
        "Cargo.toml should use the project name"
    );
}

#[test]
fn service_generates_module() {
    let project = codegen_ok(
        r#"
service MyService {
    states: Init -> Running -> Stopped

    operation Start {
        requires: true
    }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("mod myservice"),
        "should contain service module"
    );
    // S008: typestate encoding generates marker structs instead of State enum
    assert!(
        lib.contains("pub struct Init"),
        "should contain state marker struct Init: {lib}"
    );
    assert!(
        lib.contains("PhantomData"),
        "should contain PhantomData for typestate: {lib}"
    );
}

#[test]
fn service_state_transition_codegen() {
    let project = codegen_ok(
        r#"
service Connection {
    states: Disconnected -> Connected -> Closed

    operation Connect {
        requires { self.state == Disconnected }
        ensures { self.state == Connected }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    // S008: typestate encoding puts Connect in impl Connection<Disconnected>
    assert!(
        lib.contains("impl Connection<Disconnected>"),
        "should contain state-specific impl block: {lib}"
    );
    // Return type encodes the transition to Connected
    assert!(
        lib.contains("Connection<Connected>"),
        "should contain transition return type: {lib}"
    );
    // Method consumes self (not &mut self)
    assert!(
        lib.contains("fn Connect(self)"),
        "state-transitioning method should consume self: {lib}"
    );
}

#[test]
fn cargo_toml_well_formed() {
    let project = codegen_ok("");
    assert!(project.cargo_toml.contains("[package]"));
    assert!(project.cargo_toml.contains("edition = \"2024\""));
    assert!(project.cargo_toml.contains("[dependencies]"));
}

// -----------------------------------------------------------------------
// T020: Type mapping tests
// -----------------------------------------------------------------------

#[test]
fn type_mapping_int_to_i64() {
    assert_eq!(map_type_token("Int"), "i64");
}

#[test]
fn type_mapping_nat_to_u64() {
    assert_eq!(map_type_token("Nat"), "u64");
}

#[test]
fn type_mapping_float_to_f64() {
    assert_eq!(map_type_token("Float"), "f64");
}

#[test]
fn type_mapping_bool() {
    assert_eq!(map_type_token("Bool"), "bool");
}

#[test]
fn type_mapping_string() {
    assert_eq!(map_type_token("String"), "String");
}

#[test]
fn type_mapping_bytes_to_vec_u8() {
    assert_eq!(map_type_token("Bytes"), "Vec<u8>");
}

#[test]
fn type_mapping_unit() {
    assert_eq!(map_type_token("Unit"), "()");
}

#[test]
fn type_mapping_never() {
    assert_eq!(map_type_token("Never"), "!");
}

#[test]
fn type_mapping_list_to_vec() {
    assert_eq!(map_type_token("List"), "Vec");
}

#[test]
fn type_mapping_map_to_btreemap() {
    assert_eq!(map_type_token("Map"), "std::collections::BTreeMap");
}

#[test]
fn type_mapping_set_to_btreeset() {
    assert_eq!(map_type_token("Set"), "std::collections::BTreeSet");
}

#[test]
fn type_mapping_option_passthrough() {
    assert_eq!(map_type_token("Option"), "Option");
}

#[test]
fn type_mapping_result_passthrough() {
    assert_eq!(map_type_token("Result"), "Result");
}

#[test]
fn type_mapping_fixed_width() {
    assert_eq!(map_type_token("U8"), "u8");
    assert_eq!(map_type_token("U16"), "u16");
    assert_eq!(map_type_token("U32"), "u32");
    assert_eq!(map_type_token("U64"), "u64");
    assert_eq!(map_type_token("I8"), "i8");
    assert_eq!(map_type_token("I16"), "i16");
    assert_eq!(map_type_token("I32"), "i32");
    assert_eq!(map_type_token("I64"), "i64");
    assert_eq!(map_type_token("F32"), "f32");
    assert_eq!(map_type_token("F64"), "f64");
}

#[test]
fn refined_type_generates_newtype() {
    let project = codegen_ok(
        r#"
type Pos = { n: Int | n > 0 }
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("struct Pos"),
        "refined type should generate a newtype struct"
    );
    assert!(lib.contains("i64"), "refined type base should be i64");
}

#[test]
fn type_alias_codegen() {
    let project = codegen_ok(
        r#"
type UserId = Int
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("UserId"), "should contain type alias name");
}

// -----------------------------------------------------------------------
// T021: Contract codegen tests
// -----------------------------------------------------------------------

#[test]
fn contract_ensures_generates_debug_assert() {
    let project = codegen_ok(
        r#"
contract NonNeg {
    requires { true }
    ensures  { true }
}
"#,
    );
    let lib = &project.files[0].1;
    // Both requires and ensures should produce debug_assert!
    let assert_count = lib.matches("debug_assert!").count();
    assert!(
        assert_count >= 2,
        "should have debug_assert for both requires and ensures, got {assert_count}"
    );
}

#[test]
fn contract_has_result_variable() {
    let project = codegen_ok(
        r#"
contract Foo {
    requires { true }
    ensures  { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("__result"),
        "contract should declare __result variable"
    );
}

#[test]
fn fn_def_ensures_generates_debug_assert() {
    // Note: clauses must be outside the body block for the parser
    // to parse them as structured Clause objects.
    let project =
        codegen_ok("fn abs(n: Int) -> Int\n    requires { true }\n    ensures  { result >= 0 }\n");
    let lib = &project.files[0].1;
    // requires and ensures should both be debug_assert!
    let assert_count = lib.matches("debug_assert!").count();
    assert!(
        assert_count >= 2,
        "fn should have debug_assert for both requires and ensures, got {assert_count}"
    );
    assert!(
        lib.contains("__result"),
        "fn should declare __result variable"
    );
}

#[test]
fn fn_result_maps_to_dunder_result() {
    let project = codegen_ok("fn double(n: Int) -> Int\n    ensures { result == n + n }\n");
    let lib = &project.files[0].1;
    assert!(
        lib.contains("__result"),
        "result keyword in ensures should map to __result"
    );
}

// -----------------------------------------------------------------------
// T022: Cargo project generation tests
// -----------------------------------------------------------------------

#[test]
fn cargo_toml_has_package_name() {
    let project = codegen_ok(
        r#"
project test_project {
    profile: [core]
}
"#,
    );
    assert!(project.cargo_toml.contains("test_project"));
    assert!(project.cargo_toml.contains("[package]"));
}

#[test]
fn default_project_name_is_generated() {
    let project = codegen_ok("");
    assert!(
        project.cargo_toml.contains("\"generated\""),
        "default project name should be 'generated'"
    );
}

#[test]
fn generated_file_is_src_lib_rs() {
    let project = codegen_ok(
        r#"
type X {
    val: Int
}
"#,
    );
    assert_eq!(project.files.len(), 1);
    assert_eq!(project.files[0].0, "src/lib.rs");
}

#[test]
fn generated_rust_has_header_comment() {
    let project = codegen_ok("");
    let lib = &project.files[0].1;
    assert!(lib.contains("Generated by the Assura compiler"));
    assert!(lib.contains("Do not edit manually"));
}

// -----------------------------------------------------------------------
// T023: Struct and enum codegen tests
// -----------------------------------------------------------------------

#[test]
fn struct_has_derive_debug_clone_partialeq() {
    let project = codegen_ok(
        r#"
type Pair {
    a: Int
    b: Int
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("Debug"), "struct should derive Debug");
    assert!(lib.contains("Clone"), "struct should derive Clone");
    assert!(lib.contains("PartialEq"), "struct should derive PartialEq");
}

#[test]
fn struct_field_types_are_mapped() {
    let project = codegen_ok(
        r#"
type Config {
    name: String
    count: Nat
    enabled: Bool
    ratio: Float
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("String"), "String should map to String");
    assert!(lib.contains("u64"), "Nat should map to u64");
    assert!(lib.contains("bool"), "Bool should map to bool");
    assert!(lib.contains("f64"), "Float should map to f64");
}

#[test]
fn struct_pub_field_visibility() {
    let project = codegen_ok(
        r#"
type Visible {
    pub x: Int
    y: Int
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("pub x"),
        "pub field should have pub visibility in generated code"
    );
}

#[test]
fn enum_has_derive_debug_clone_partialeq() {
    let project = codegen_ok(
        r#"
enum Direction {
    North,
    South,
    East,
    West
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("Debug"), "enum should derive Debug");
    assert!(lib.contains("Clone"), "enum should derive Clone");
    assert!(lib.contains("PartialEq"), "enum should derive PartialEq");
}

#[test]
fn enum_variant_with_data() {
    let project = codegen_ok(
        r#"
enum Value {
    Num(Int),
    Text(String),
    Nothing
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("Num"), "should contain Num variant");
    assert!(lib.contains("i64"), "Int should map to i64 in variant");
    assert!(lib.contains("Text"), "should contain Text variant");
    assert!(
        lib.contains("Nothing"),
        "should contain unit variant Nothing"
    );
}

#[test]
fn empty_struct_codegen() {
    let project = codegen_ok(
        r#"
type Marker {
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("Marker"), "should contain empty struct");
}

// -----------------------------------------------------------------------
// T028: End-to-end SafeDivision contract test
// -----------------------------------------------------------------------

#[test]
fn e2e_safe_division_check_passes() {
    // Parse the e2e test file through the full pipeline
    let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
        .expect("failed to read safe_division.assura");
    let file = assura_parser::parse_unwrap(&source);
    let resolved = assura_resolve::resolve(&file).expect("resolution should succeed");
    let typed = assura_types::type_check(&resolved).expect("type check should succeed");

    // Codegen should succeed
    let project = codegen(&typed);
    assert!(
        !project.cargo_toml.is_empty(),
        "Cargo.toml should not be empty"
    );
    assert_eq!(
        project.files.len(),
        1,
        "should produce exactly one source file"
    );
    assert_eq!(project.files[0].0, "src/lib.rs");
}

#[test]
fn e2e_safe_division_generates_debug_assert_for_requires() {
    let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
        .expect("failed to read safe_division.assura");
    let project = codegen_ok(&source);
    let lib = &project.files[0].1;

    // The requires clause `b != 0` must produce a debug_assert
    assert!(
        lib.contains("debug_assert!"),
        "generated code must contain debug_assert!"
    );
    assert!(
        lib.contains("b != 0"),
        "generated code must contain the requires predicate 'b != 0'"
    );
}

#[test]
fn e2e_safe_division_generates_ensures_assertion() {
    let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
        .expect("failed to read safe_division.assura");
    let project = codegen_ok(&source);
    let lib = &project.files[0].1;

    // The ensures clause should produce a debug_assert with the postcondition
    assert!(
        lib.contains("debug_assert!"),
        "generated code must contain debug_assert from requires/ensures"
    );
    // At least two debug_assert! calls: for requires and ensures
    let assert_count = lib.matches("debug_assert!").count();
    assert!(
        assert_count >= 2,
        "should have debug_assert for both requires and ensures, got {assert_count}"
    );
}

#[test]
fn e2e_safe_division_has_correct_signature() {
    let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
        .expect("failed to read safe_division.assura");
    let project = codegen_ok(&source);
    let lib = &project.files[0].1;

    // Should have input params mapped to i64
    assert!(lib.contains("a: i64"), "input param 'a' should map to i64");
    assert!(lib.contains("b: i64"), "input param 'b' should map to i64");
    // Should have the contract module
    assert!(
        lib.contains("contract_safedivision"),
        "should contain the SafeDivision contract module"
    );
}

#[test]
fn e2e_safe_division_generated_rust_is_valid() {
    let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
        .expect("failed to read safe_division.assura");
    let project = codegen_ok(&source);
    let lib = &project.files[0].1;

    // Verify the generated Rust parses as valid syntax via syn
    syn::parse_file(lib).expect("generated Rust should be valid syntax");
}

// -----------------------------------------------------------------------
// T043 CORE.1: Ghost code erasure tests
// -----------------------------------------------------------------------

#[test]
fn ghost_fn_produces_no_output() {
    // A ghost function should be completely erased in generated code.
    let project =
        codegen_ok("ghost fn spec_helper(x: Int) -> Bool\n    ensures { result == true }\n");
    let lib = &project.files[0].1;
    assert!(
        !lib.contains("fn spec_helper"),
        "ghost fn should not appear in generated Rust code"
    );
}

#[test]
fn non_ghost_fn_still_generated() {
    // A normal (non-ghost) function should still be generated.
    let project = codegen_ok("fn normal_helper(x: Int) -> Int\n    ensures { result >= 0 }\n");
    let lib = &project.files[0].1;
    assert!(
        lib.contains("fn normal_helper"),
        "non-ghost fn should appear in generated Rust code"
    );
}

#[test]
fn ghost_block_erased_in_expr() {
    // A ghost block expression should produce erased output.
    let expr = Expr::Ghost(Box::new(Expr::Literal(Literal::Bool(true))));
    let rust = expr_to_rust(&expr);
    assert!(
        rust.contains("ghost erased"),
        "ghost block should generate erased marker, got: {rust}"
    );
}

// -----------------------------------------------------------------------
// T044 CORE.2: Lemma erasure tests
// -----------------------------------------------------------------------

#[test]
fn lemma_fn_produces_no_output() {
    // A lemma function should be completely erased in generated code.
    let project = codegen_ok("lemma add_comm(a: Int, b: Int)\n    ensures { a + b == b + a }\n");
    let lib = &project.files[0].1;
    assert!(
        !lib.contains("fn add_comm"),
        "lemma fn should not appear in generated Rust code"
    );
}

#[test]
fn apply_expr_erased_in_codegen() {
    // apply lemma_name(args) should produce a comment, not code.
    let expr = Expr::Apply {
        lemma_name: "my_lemma".into(),
        args: vec![Expr::Literal(Literal::Int("42".into()))],
    };
    let rust = expr_to_rust(&expr);
    assert!(
        rust.contains("lemma my_lemma applied"),
        "apply should generate erased comment, got: {rust}"
    );
}

#[test]
fn match_expr_codegen() {
    // match expression should generate Rust match syntax
    let expr = Expr::Match {
        scrutinee: Box::new(Expr::Ident("status".into())),
        arms: vec![
            assura_parser::ast::MatchArm {
                pattern: assura_parser::ast::Pattern::Ident("Active".into()),
                body: Expr::Literal(Literal::Int("1".into())),
            },
            assura_parser::ast::MatchArm {
                pattern: assura_parser::ast::Pattern::Wildcard,
                body: Expr::Literal(Literal::Int("0".into())),
            },
        ],
    };
    let rust = expr_to_rust(&expr);
    assert!(
        rust.contains("match status"),
        "should have match keyword: {rust}"
    );
    assert!(
        rust.contains("Active => 1"),
        "should have Active arm: {rust}"
    );
    assert!(rust.contains("_ => 0"), "should have wildcard arm: {rust}");
}

#[test]
fn match_without_wildcard_gets_fallback() {
    // match with only Constructor patterns (no wildcard) should get _ => unreachable!()
    let expr = Expr::Match {
        scrutinee: Box::new(Expr::Ident("color".into())),
        arms: vec![
            assura_parser::ast::MatchArm {
                pattern: assura_parser::ast::Pattern::Constructor {
                    name: "Red".into(),
                    fields: vec![],
                },
                body: Expr::Literal(Literal::Int("1".into())),
            },
            assura_parser::ast::MatchArm {
                pattern: assura_parser::ast::Pattern::Constructor {
                    name: "Blue".into(),
                    fields: vec![],
                },
                body: Expr::Literal(Literal::Int("2".into())),
            },
        ],
    };
    let rust = expr_to_rust(&expr);
    assert!(
        rust.contains("_ => unreachable!"),
        "match without wildcard should get fallback: {rust}"
    );
}

#[test]
fn non_lemma_fn_still_generated() {
    // A normal (non-lemma) function should still be generated.
    let project = codegen_ok("fn helper(n: Int) -> Int\n    ensures { result >= 0 }\n");
    let lib = &project.files[0].1;
    assert!(
        lib.contains("fn helper"),
        "non-lemma fn should appear in generated Rust code"
    );
}

// =======================================================================
// T119: Cranelift backend configuration
// =======================================================================

#[test]
fn backend_default_is_rustc() {
    let config = super::BackendConfig::default();
    assert_eq!(config.backend, super::CodegenBackend::Rustc);
}

#[test]
fn backend_cranelift_fast_dev() {
    let config = super::BackendConfig {
        backend: super::CodegenBackend::Cranelift,
        opt_level: 0,
        debug_info: true,
        target: super::CompileTarget::Native,
    };
    assert_eq!(config.backend, super::CodegenBackend::Cranelift);
    assert_eq!(config.opt_level, 0);
}

fn codegen_with_config_ok(source: &str, config: super::BackendConfig) -> super::GeneratedProject {
    let file = assura_parser::parse_unwrap(source);
    let resolved = assura_resolve::resolve(&file).expect("resolve failed");
    let typed = assura_types::type_check(&resolved).expect("type check failed");
    super::codegen_with_config(&typed, &config)
}

#[test]
fn cranelift_generates_cargo_config() {
    let source = "contract Add { requires(a: Int, b: Int) ensures(result: Int) }";
    let project = codegen_with_config_ok(
        source,
        super::BackendConfig {
            backend: super::CodegenBackend::Cranelift,
            opt_level: 0,
            debug_info: true,
            target: super::CompileTarget::Native,
        },
    );
    let cargo_config = project
        .files
        .iter()
        .find(|(path, _)| path == ".cargo/config.toml")
        .expect(".cargo/config.toml should be generated for Cranelift backend");
    assert!(
        cargo_config.1.contains("codegen-backend = \"cranelift\""),
        "config.toml should select cranelift backend"
    );
}

#[test]
fn cranelift_output_differs_from_rustc() {
    let source = "contract Add { requires(a: Int, b: Int) ensures(result: Int) }";
    let rustc_project = codegen_ok(source);
    let cranelift_project = codegen_with_config_ok(
        source,
        super::BackendConfig {
            backend: super::CodegenBackend::Cranelift,
            opt_level: 0,
            debug_info: true,
            target: super::CompileTarget::Native,
        },
    );
    assert!(
        cranelift_project.files.len() > rustc_project.files.len(),
        "Cranelift should produce .cargo/config.toml that Rustc does not"
    );
}

#[test]
fn rustc_has_no_cargo_config() {
    let source = "contract Add { requires(a: Int, b: Int) ensures(result: Int) }";
    let project = codegen_ok(source);
    assert!(
        !project
            .files
            .iter()
            .any(|(path, _)| path.contains("config.toml")),
        "Rustc backend should not produce .cargo/config.toml"
    );
}

// =======================================================================
// Generated Rust compilation tests
// =======================================================================

/// Verify generated Rust for a contract parses as valid Rust syntax.
fn assert_generated_rust_valid(source: &str) {
    let project = codegen_ok(source);
    let lib = &project.files[0].1;
    syn::parse_file(lib).unwrap_or_else(|e| {
        panic!("generated Rust is not valid syntax:\n{lib}\n\nerror: {e}");
    });
}

#[test]
fn generated_rust_contract_is_valid() {
    assert_generated_rust_valid(
        r#"
contract SafeDivision {
  input(a: Int, b: Int)
  output(result: Int)
  requires { b != 0 }
  ensures { result * b == a }
  effects { pure }
}
"#,
    );
}

#[test]
fn generated_rust_fn_is_valid() {
    assert_generated_rust_valid(
        r#"
fn clamp(x: Int, lo: Int, hi: Int) -> Int
  requires { lo <= hi }
  ensures { result >= lo && result <= hi }
{
  if x < lo then lo else if x > hi then hi else x
}
"#,
    );
}

#[test]
fn generated_rust_service_is_valid() {
    let source = std::fs::read_to_string("../assura-cli/../../tests/fixtures/service_full.assura")
        .unwrap_or_else(|_| {
            std::fs::read_to_string("tests/fixtures/service_full.assura")
                .expect("cannot find service_full fixture")
        });
    let project = codegen_ok(&source);
    let lib = &project.files[0].1;
    syn::parse_file(lib).unwrap_or_else(|e| {
        panic!("service generated Rust is not valid:\n{lib}\n\nerror: {e}");
    });
}

#[test]
fn generated_rust_demo_libwebp_is_valid() {
    let source = std::fs::read_to_string("../assura-cli/../../demos/libwebp-huffman.assura")
        .unwrap_or_else(|_| {
            // Fallback path when running from workspace root
            std::fs::read_to_string("demos/libwebp-huffman.assura")
                .expect("cannot find libwebp demo")
        });
    let project = codegen_ok(&source);
    let lib = &project.files[0].1;
    syn::parse_file(lib).unwrap_or_else(|e| {
        panic!("libwebp generated Rust is not valid:\n{lib}\n\nerror: {e}");
    });
}

#[test]
fn codegen_with_config_produces_profile() {
    let config = super::BackendConfig {
        backend: super::CodegenBackend::Rustc,
        opt_level: 3,
        debug_info: true,
        target: super::CompileTarget::Native,
    };
    let project = {
        let file = assura_parser::parse_unwrap("");
        let resolved = assura_resolve::resolve(&file).expect("resolve failed");
        let typed = assura_types::type_check(&resolved).expect("type check failed");
        super::codegen_with_config(&typed, &config)
    };
    assert!(project.cargo_toml.contains("opt-level = 3"));
    assert!(project.cargo_toml.contains("debug = true"));
}

#[test]
fn pattern_to_rust_constructor_with_fields() {
    use assura_parser::ast::Pattern;
    let pat = Pattern::Constructor {
        name: "Some".into(),
        fields: vec![Pattern::Ident("x".into())],
    };
    assert_eq!(super::pattern_to_rust(&pat), "Some(x)");
}

#[test]
fn pattern_to_rust_constructor_no_fields() {
    use assura_parser::ast::Pattern;
    let pat = Pattern::Constructor {
        name: "None".into(),
        fields: vec![],
    };
    assert_eq!(super::pattern_to_rust(&pat), "None");
}

#[test]
fn pattern_to_rust_nested_constructor() {
    use assura_parser::ast::Pattern;
    let pat = Pattern::Constructor {
        name: "Ok".into(),
        fields: vec![Pattern::Constructor {
            name: "Some".into(),
            fields: vec![Pattern::Ident("v".into())],
        }],
    };
    assert_eq!(super::pattern_to_rust(&pat), "Ok(Some(v))");
}

#[test]
fn pattern_to_rust_tuple_nested() {
    use assura_parser::ast::Pattern;
    let pat = Pattern::Tuple(vec![
        Pattern::Ident("a".into()),
        Pattern::Tuple(vec![Pattern::Ident("b".into()), Pattern::Wildcard]),
    ]);
    assert_eq!(super::pattern_to_rust(&pat), "(a, (b, _))");
}

// =======================================================================
// Interface trait generation tests (T062)
// =======================================================================

#[test]
fn interface_block_generates_trait() {
    let mut code = String::new();
    let body = vec![
        Clause {
            kind: ClauseKind::Other("method".into()),
            body: Expr::Ident("process".into()),
            effect_variables: vec![],
        },
        Clause {
            kind: ClauseKind::Other("method".into()),
            body: Expr::Ident("validate".into()),
            effect_variables: vec![],
        },
    ];
    super::generate_interface_trait("Processor", &body, &mut code);
    assert!(
        code.contains("pub trait Processor"),
        "should generate trait: {code}"
    );
    assert!(
        code.contains("fn process(&self)"),
        "should have process method: {code}"
    );
    assert!(
        code.contains("fn validate(&self)"),
        "should have validate method: {code}"
    );
}

#[test]
fn interface_with_extends_generates_supertrait() {
    let mut code = String::new();
    let body = vec![
        Clause {
            kind: ClauseKind::Other("extends".into()),
            body: Expr::Ident("Base".into()),
            effect_variables: vec![],
        },
        Clause {
            kind: ClauseKind::Other("method".into()),
            body: Expr::Ident("extra".into()),
            effect_variables: vec![],
        },
    ];
    super::generate_interface_trait("Extended", &body, &mut code);
    assert!(
        code.contains("pub trait Extended: Base"),
        "should have supertrait bound: {code}"
    );
}

#[test]
fn interface_with_invariant_generates_provided_method() {
    let mut code = String::new();
    let body = vec![Clause {
        kind: ClauseKind::Invariant,
        body: Expr::BinOp {
            lhs: Box::new(Expr::Ident("x".into())),
            op: BinOp::Gt,
            rhs: Box::new(Expr::Literal(Literal::Int("0".into()))),
        },
        effect_variables: vec![],
    }];
    super::generate_interface_trait("Positive", &body, &mut code);
    assert!(
        code.contains("fn check_invariant"),
        "should generate invariant check: {code}"
    );
    assert!(
        code.contains("debug_assert!"),
        "should contain debug_assert: {code}"
    );
}

#[test]
fn interface_contract_generates_trait() {
    // Contract with an `interface` clause should produce a trait, not a module
    let source = r#"
contract Sortable {
  interface: true
  method: compare
  method: swap
}
"#;
    let project = codegen_ok(source);
    let lib = &project.files[0].1;
    assert!(
        lib.contains("trait Sortable"),
        "interface contract should generate trait: {lib}"
    );
    assert!(
        !lib.contains("mod contract_sortable"),
        "interface contract should NOT generate module: {lib}"
    );
}

#[test]
fn implements_contract_generates_impl_block() {
    // Contract with `implements` clause should generate struct + impl.
    // With 2 contracts this triggers multi-file mode.
    let source = r#"
contract Sortable {
  interface: true
  method: compare
}

contract MySorter {
  implements: Sortable
  method: compare
  requires { x > 0 }
}
"#;
    let project = codegen_ok(source);

    // Multi-file mode: lib.rs has mod declarations, contract files have contents
    let find_file = |name: &str| -> &str {
        &project
            .files
            .iter()
            .find(|(p, _)| p == name)
            .unwrap_or_else(|| {
                panic!(
                    "missing file {name}: files={:?}",
                    project.files.iter().map(|(p, _)| p).collect::<Vec<_>>()
                )
            })
            .1
    };

    let lib = find_file("src/lib.rs");
    assert!(
        lib.contains("pub mod contract_sortable;"),
        "lib.rs should declare sortable module: {lib}"
    );
    assert!(
        lib.contains("pub mod contract_mysorter;"),
        "lib.rs should declare mysorter module: {lib}"
    );

    let sortable = find_file("src/contract_sortable.rs");
    assert!(
        sortable.contains("trait Sortable"),
        "sortable module should contain trait: {sortable}"
    );

    let mysorter = find_file("src/contract_mysorter.rs");
    assert!(
        mysorter.contains("struct MySorter"),
        "mysorter module should contain struct: {mysorter}"
    );
    assert!(
        mysorter.contains("impl Sortable for MySorter"),
        "mysorter module should contain impl block: {mysorter}"
    );
}

#[test]
fn forall_ensures_generates_iter_all() {
    let project = codegen_ok(
        r#"
contract AllPositive {
    input(values: List<Int>)
    requires { forall v in values: v > 0 }
    ensures  { forall v in result: v > 0 }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains(".iter().all("),
        "forall in ensures should generate .iter().all(): {lib}"
    );
    assert!(
        lib.contains("__result.iter().all("),
        "result in forall ensures should map to __result: {lib}"
    );
}

#[test]
fn exists_ensures_generates_iter_any() {
    let project = codegen_ok(
        r#"
contract HasPositive {
    input(values: List<Int>)
    ensures  { exists v in result: v > 0 }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains(".iter().any("),
        "exists in ensures should generate .iter().any(): {lib}"
    );
}

#[test]
fn raw_forall_tokens_converted() {
    // Test the raw_tokens_to_rust helper directly
    let tokens: Vec<String> = vec!["forall", "v", "in", "items", ":", "v", ">", "0"]
        .into_iter()
        .map(String::from)
        .collect();
    let result = raw_tokens_to_rust(&tokens);
    assert!(
        result.contains(".iter().all("),
        "raw forall tokens should produce .iter().all(): {result}"
    );
    assert!(result.contains("|v|"), "should bind variable v: {result}");
}

#[test]
fn raw_exists_tokens_converted() {
    let tokens: Vec<String> = vec!["exists", "x", "in", "data", ":", "x", "==", "target"]
        .into_iter()
        .map(String::from)
        .collect();
    let result = raw_tokens_to_rust(&tokens);
    assert!(
        result.contains(".iter().any("),
        "raw exists tokens should produce .iter().any(): {result}"
    );
}

#[test]
fn raw_result_keyword_replaced() {
    let tokens: Vec<String> = vec!["result", ">=", "0"]
        .into_iter()
        .map(String::from)
        .collect();
    let result = raw_tokens_to_rust(&tokens);
    assert!(
        result.contains("__result"),
        "result keyword in raw tokens should become __result: {result}"
    );
}

#[test]
fn enum_generates_exhaustiveness_check() {
    let project = codegen_ok(
        r#"
enum Color {
    Red,
    Green,
    Blue,
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("__exhaustive_check_color"),
        "enum should generate exhaustiveness check function: {lib}"
    );
    assert!(
        lib.contains("Color::Red =>"),
        "exhaustiveness check should cover Red variant: {lib}"
    );
    assert!(
        lib.contains("Color::Green =>"),
        "exhaustiveness check should cover Green variant: {lib}"
    );
    assert!(
        lib.contains("Color::Blue =>"),
        "exhaustiveness check should cover Blue variant: {lib}"
    );
    // Should NOT have a wildcard arm
    assert!(
        !lib.contains("_ =>"),
        "exhaustiveness check must not have a wildcard arm: {lib}"
    );
}

#[test]
fn enum_with_data_generates_exhaustiveness_check() {
    let project = codegen_ok(
        r#"
enum Value {
    Num(Int),
    Text(String),
    Empty,
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("__exhaustive_check_value"),
        "data enum should generate exhaustiveness check: {lib}"
    );
    assert!(
        lib.contains("Value::Num(_)"),
        "data variant should use wildcard field: {lib}"
    );
    assert!(
        lib.contains("Value::Empty =>"),
        "unit variant should be covered: {lib}"
    );
}

#[test]
fn extract_input_params_single_cast() {
    // Top-level Cast: input(a as Int) at top level
    let mut params = Vec::new();
    let body = Expr::Cast {
        expr: Box::new(Expr::Ident("a".into())),
        ty: "Int".into(),
    };
    extract_input_params(&body, &mut params);
    assert_eq!(params.len(), 1);
    assert_eq!(params[0].0, "a");
}

#[test]
fn extract_input_params_single_ident() {
    let mut params = Vec::new();
    let body = Expr::Ident("x".into());
    extract_input_params(&body, &mut params);
    assert_eq!(params.len(), 1);
    assert_eq!(params[0], ("x".to_string(), "i64".to_string()));
}

#[test]
fn extract_input_params_raw_as() {
    let mut params = Vec::new();
    let tokens = vec![
        "a".into(),
        "as".into(),
        "Int".into(),
        ",".into(),
        "b".into(),
        "as".into(),
        "String".into(),
    ];
    let body = Expr::Raw(tokens);
    extract_input_params(&body, &mut params);
    assert_eq!(params.len(), 2);
    assert_eq!(params[0].0, "a");
    assert_eq!(params[1].0, "b");
}

#[test]
fn extract_input_params_raw_bare_idents() {
    let mut params = Vec::new();
    let tokens = vec!["buf".into(), ",".into(), "n".into()];
    let body = Expr::Raw(tokens);
    extract_input_params(&body, &mut params);
    assert_eq!(params.len(), 2);
    assert_eq!(params[0].0, "buf");
    assert_eq!(params[1].0, "n");
}

#[test]
fn extract_output_type_paren() {
    let body = Expr::Paren(Box::new(Expr::Ident("Int".into())));
    let ty = extract_output_type(&body);
    assert_eq!(ty, "i64");
}

#[test]
fn extract_output_type_raw_as() {
    let tokens = vec!["result".into(), "as".into(), "Bool".into()];
    let body = Expr::Raw(tokens);
    let ty = extract_output_type(&body);
    assert_eq!(ty, "bool");
}

#[test]
fn contract_effects_generates_doc_comment() {
    let project = codegen_ok(
        r#"
contract Alloc {
    effects  { io }
    requires { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("/// Effects:"),
        "effects clause should produce doc comment"
    );
}

#[test]
fn contract_modifies_generates_doc_comment() {
    let project = codegen_ok(
        r#"
contract Mutator {
    modifies { buffer }
    requires { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("/// Modifies:"),
        "modifies clause should produce doc comment"
    );
}

#[test]
fn contract_requires_generates_doc_comment() {
    let project = codegen_ok(
        r#"
contract Bounded {
    requires { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("/// Requires:"),
        "requires clause should produce doc comment: {lib}"
    );
}

#[test]
fn service_operation_requires_generates_doc_comment() {
    let project = codegen_ok(
        r#"
service Validator {
    states: Idle -> Busy

    operation Validate {
        requires { true }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("/// Requires:"),
        "requires clause in service operation should produce doc comment: {lib}"
    );
}

#[test]
fn service_operation_modifies_generates_doc_comment() {
    let project = codegen_ok(
        r#"
service Storage {
    states: Empty -> Full

    operation Store {
        modifies { buffer }
        requires { true }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("/// Modifies:"),
        "modifies clause in service operation should produce doc comment: {lib}"
    );
}

#[test]
fn service_operation_invariant_generates_debug_assert() {
    let project = codegen_ok(
        r#"
service Counter {
    states: Ready -> Done

    operation Increment {
        invariant { true }
        requires  { true }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    // requires produces one debug_assert, invariant produces another
    let assert_count = lib.matches("debug_assert!").count();
    assert!(
        assert_count >= 2,
        "should have debug_assert for both requires and invariant, got {assert_count}: {lib}"
    );
}

#[test]
fn contract_invariant_generates_debug_assert() {
    let project = codegen_ok(
        r#"
contract Stable {
    invariant { true }
    requires  { true }
}
"#,
    );
    let lib = &project.files[0].1;
    // requires produces one debug_assert, invariant produces another
    let assert_count = lib.matches("debug_assert!").count();
    assert!(
        assert_count >= 2,
        "should have debug_assert for both requires and invariant, got {assert_count}"
    );
}

// S008: Typestate codegen tests

#[test]
fn s008_typestate_marker_structs_generated() {
    let project = codegen_ok(
        r#"
service Door {
    states: Locked -> Unlocked -> Open
    operation Unlock {
        requires { self.state == Locked }
        ensures { self.state == Unlocked }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("pub struct Locked"),
        "should generate Locked marker struct: {lib}"
    );
    assert!(
        lib.contains("pub struct Unlocked"),
        "should generate Unlocked marker struct: {lib}"
    );
    assert!(
        lib.contains("pub struct Open"),
        "should generate Open marker struct: {lib}"
    );
    // Should NOT generate enum State
    assert!(
        !lib.contains("enum State"),
        "typestate should not generate enum State: {lib}"
    );
}

#[test]
fn s008_typestate_generic_struct_with_phantom() {
    let project = codegen_ok(
        r#"
service Door {
    states: Locked -> Unlocked
    operation Unlock {
        requires { self.state == Locked }
        ensures { self.state == Unlocked }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("struct Door<State>"),
        "service struct should be generic: {lib}"
    );
    assert!(
        lib.contains("PhantomData<State>"),
        "struct should contain PhantomData: {lib}"
    );
}

#[test]
fn s008_typestate_constructor_on_initial_state() {
    let project = codegen_ok(
        r#"
service Workflow {
    states: Pending -> Active -> Complete
    operation Activate {
        requires { self.state == Pending }
        ensures { self.state == Active }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("impl Workflow<Pending>"),
        "new() should be on initial state impl block: {lib}"
    );
    assert!(
        lib.contains("fn new()"),
        "should generate constructor: {lib}"
    );
}

#[test]
fn s008_typestate_transition_consumes_self() {
    let project = codegen_ok(
        r#"
service Conn {
    states: Idle -> Active -> Closed
    operation Open {
        requires { self.state == Idle }
        ensures { self.state == Active }
    }
    operation Close {
        requires { self.state == Active }
        ensures { self.state == Closed }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    // Open should be on impl Conn<Idle> and return Conn<Active>
    assert!(
        lib.contains("impl Conn<Idle>"),
        "Open should be in Idle impl: {lib}"
    );
    assert!(
        lib.contains("fn Open(self) -> Conn<Active>"),
        "Open should consume self and return Conn<Active>: {lib}"
    );
    // Close should be on impl Conn<Active> and return Conn<Closed>
    assert!(
        lib.contains("impl Conn<Active>"),
        "Close should be in Active impl: {lib}"
    );
    assert!(
        lib.contains("fn Close(self) -> Conn<Closed>"),
        "Close should consume self and return Conn<Closed>: {lib}"
    );
}

#[test]
fn s008_typestate_stateless_service_unchanged() {
    let project = codegen_ok(
        r#"
service Simple {
    operation DoWork {
        requires { true }
    }
}
"#,
    );
    let lib = &project.files[0].1;
    // Stateless service should NOT have PhantomData or marker structs
    assert!(
        !lib.contains("PhantomData"),
        "stateless service should not use PhantomData: {lib}"
    );
    assert!(
        lib.contains("struct Simple"),
        "stateless service should have simple struct: {lib}"
    );
    assert!(
        lib.contains("fn new()"),
        "stateless service should have constructor: {lib}"
    );
}

#[test]
fn s008_typestate_query_uses_ref_self() {
    let project = codegen_ok(
        r#"
service Store {
    states: Ready -> Done
    query GetCount {
        output(count: Nat)
    }
}
"#,
    );
    let lib = &project.files[0].1;
    // Query without state guard goes in generic impl
    assert!(
        lib.contains("impl<S> Store<S>"),
        "state-independent query should be in generic impl: {lib}"
    );
    assert!(lib.contains("&self"), "query should use &self: {lib}");
}

// S009: Proptest generation tests

#[test]
fn s009_proptest_generated_for_contract_with_requires_ensures() {
    let project = codegen_ok(
        r#"
contract SafeDivision {
    input(a: Int, b: Int)
    requires { b != 0 }
    ensures { result * b + (a % b) == a }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("proptest!"),
        "should generate proptest macro: {lib}"
    );
    assert!(
        lib.contains("prop_assert!"),
        "ensures should become prop_assert: {lib}"
    );
    assert!(
        lib.contains("#[cfg(test)]"),
        "proptest module should be gated: {lib}"
    );
}

#[test]
fn s009_proptest_refines_strategy_for_neq_zero() {
    let project = codegen_ok(
        r#"
contract Div {
    input(a: Int, b: Int)
    requires { b != 0 }
    ensures { true }
}
"#,
    );
    let lib = &project.files[0].1;
    // b != 0 should be refined to a range strategy, not prop_assume
    // prettyplease may break the range across lines, so check components
    assert!(
        lib.contains("1i64") && lib.contains("i64::MAX"),
        "b != 0 should refine to positive range: {lib}"
    );
    // Should NOT have prop_assume for b since it was refined
    assert!(
        !lib.contains("prop_assume!"),
        "refined requires should not produce prop_assume: {lib}"
    );
}

#[test]
fn s009_proptest_unrefined_requires_becomes_prop_assume() {
    let project = codegen_ok(
        r#"
contract Complex {
    input(x: Int)
    requires { x * x > 10 }
    ensures { true }
}
"#,
    );
    let lib = &project.files[0].1;
    // Complex requires can't be refined, should become prop_assume
    assert!(
        lib.contains("prop_assume!"),
        "complex requires should become prop_assume: {lib}"
    );
}

#[test]
fn s009_proptest_not_generated_without_ensures() {
    let project = codegen_ok(
        r#"
contract NoEnsures {
    input(x: Int)
    requires { x > 0 }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        !lib.contains("proptest!"),
        "contract without ensures should not generate proptest: {lib}"
    );
}

#[test]
fn s009_proptest_not_generated_without_input() {
    let project = codegen_ok(
        r#"
contract NoInput {
    ensures { true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        !lib.contains("proptest!"),
        "contract without input should not generate proptest: {lib}"
    );
}

#[test]
fn s009_cargo_toml_has_proptest_dev_dependency() {
    let project = codegen_ok(
        r#"
contract Testable {
    input(x: Int)
    ensures { true }
}
"#,
    );
    assert!(
        project.cargo_toml.contains("proptest"),
        "Cargo.toml should include proptest dev-dependency: {}",
        project.cargo_toml
    );
    assert!(
        project.cargo_toml.contains("[dev-dependencies]"),
        "should have dev-dependencies section: {}",
        project.cargo_toml
    );
}

#[test]
fn s009_cargo_toml_no_proptest_when_not_needed() {
    let project = codegen_ok(
        r#"
contract NotTestable {
    requires { true }
}
"#,
    );
    assert!(
        !project.cargo_toml.contains("proptest"),
        "Cargo.toml should not include proptest when no testable contracts: {}",
        project.cargo_toml
    );
}

// R002: Multi-file codegen tests

#[test]
fn single_contract_stays_in_lib_rs() {
    // A file with only one contract should produce a single lib.rs
    let project = codegen_ok(
        r#"
contract OnlyOne {
    input(x: Int)
    requires { x > 0 }
}
"#,
    );
    assert_eq!(project.files.len(), 1, "single contract = single file");
    assert_eq!(project.files[0].0, "src/lib.rs");
    assert!(
        project.files[0].1.contains("pub mod contract_onlyone"),
        "single contract should have inline module in lib.rs"
    );
}

#[test]
fn multi_contract_generates_separate_files() {
    let project = codegen_ok(
        r#"
type Point {
    x: Int
    y: Int
}

contract Alpha {
    input(a: Int)
    requires { a > 0 }
}

contract Beta {
    input(b: Int)
    ensures { result > 0 }
}
"#,
    );
    // Should produce: lib.rs, contract_alpha.rs, contract_beta.rs
    assert_eq!(
        project.files.len(),
        3,
        "two contracts = 3 files: {:?}",
        project.files.iter().map(|(p, _)| p).collect::<Vec<_>>()
    );

    let find_file = |name: &str| -> &str {
        &project
            .files
            .iter()
            .find(|(p, _)| p == name)
            .unwrap_or_else(|| {
                panic!(
                    "missing {name}: {:?}",
                    project.files.iter().map(|(p, _)| p).collect::<Vec<_>>()
                )
            })
            .1
    };

    let lib = find_file("src/lib.rs");
    // Shared types stay in lib.rs
    assert!(lib.contains("struct Point"), "shared type in lib.rs");
    // Module declarations for contracts
    assert!(
        lib.contains("pub mod contract_alpha;"),
        "lib.rs declares alpha module"
    );
    assert!(
        lib.contains("pub mod contract_beta;"),
        "lib.rs declares beta module"
    );
    // Contracts themselves should NOT be in lib.rs
    assert!(
        !lib.contains("pub fn check(a: i64)"),
        "contract body should not be inline in lib.rs"
    );

    let alpha = find_file("src/contract_alpha.rs");
    assert!(alpha.contains("use super::*"), "module imports parent");
    assert!(
        alpha.contains("pub fn check(a: i64)"),
        "alpha has check fn: {alpha}"
    );

    let beta = find_file("src/contract_beta.rs");
    assert!(
        beta.contains("pub fn check(b: i64)"),
        "beta has check fn: {beta}"
    );
}

#[test]
fn multi_file_with_service() {
    let project = codegen_ok(
        r#"
contract Guard {
    input(x: Int)
    requires { x >= 0 }
}

service Counter {
    states: Idle -> Running -> Done
    operation Start {
        requires: true
        effects: io
    }
}
"#,
    );
    // contract + service = 2 modules -> multi-file
    assert_eq!(
        project.files.len(),
        3,
        "contract + service = 3 files: {:?}",
        project.files.iter().map(|(p, _)| p).collect::<Vec<_>>()
    );

    let find_file = |name: &str| -> &str {
        &project
            .files
            .iter()
            .find(|(p, _)| p == name)
            .unwrap_or_else(|| {
                panic!(
                    "missing {name}: {:?}",
                    project.files.iter().map(|(p, _)| p).collect::<Vec<_>>()
                )
            })
            .1
    };

    let lib = find_file("src/lib.rs");
    assert!(lib.contains("pub mod contract_guard;"));
    assert!(lib.contains("pub mod counter;"));

    let guard = find_file("src/contract_guard.rs");
    assert!(guard.contains("pub fn check"));

    let counter = find_file("src/counter.rs");
    assert!(counter.contains("struct Counter"));
    // S008: typestate encoding generates marker structs, not enum State
    assert!(
        counter.contains("pub struct Idle"),
        "should contain state marker struct: {counter}"
    );
}

#[test]
fn multi_file_shared_types_not_duplicated() {
    // Types, enums, and externs stay in lib.rs, not in contract files
    let project = codegen_ok(
        r#"
type MyData {
    value: Int
}

enum Status {
    Active,
    Inactive
}

contract First {
    input(x: Int)
    requires { x > 0 }
}

contract Second {
    input(y: Int)
    ensures { result > 0 }
}
"#,
    );

    let find_file = |name: &str| -> &str {
        &project
            .files
            .iter()
            .find(|(p, _)| p == name)
            .unwrap_or_else(|| {
                panic!(
                    "missing {name}: {:?}",
                    project.files.iter().map(|(p, _)| p).collect::<Vec<_>>()
                )
            })
            .1
    };

    let lib = find_file("src/lib.rs");
    assert!(
        lib.contains("struct MyData"),
        "shared type in lib.rs: {lib}"
    );
    assert!(lib.contains("enum Status"), "shared enum in lib.rs: {lib}");

    let first = find_file("src/contract_first.rs");
    assert!(
        !first.contains("struct MyData"),
        "type should not be in contract file"
    );
    assert!(
        !first.contains("enum Status"),
        "enum should not be in contract file"
    );
}

// --- P004: Error handling codegen tests ---

#[test]
fn contract_with_errors_generates_error_enum() {
    let project = codegen_ok(
        r#"
contract SafeDivision {
    input  { a: Int, b: Int }
    output { result: Int }
    errors { DivByZero, Overflow }
    requires { b != 0 }
    ensures  { result * b == a }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("SafeDivisionError"),
        "should generate error enum: {lib}"
    );
    assert!(
        lib.contains("DivByZero"),
        "should contain DivByZero variant: {lib}"
    );
    assert!(
        lib.contains("Overflow"),
        "should contain Overflow variant: {lib}"
    );
    assert!(
        lib.contains("thiserror::Error"),
        "should derive thiserror::Error: {lib}"
    );
}

#[test]
fn contract_with_errors_returns_result() {
    let project = codegen_ok(
        r#"
contract Validator {
    input  { data: Int }
    output { result: Bool }
    errors { InvalidInput }
    ensures { result == true }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(lib.contains("Result<"), "should return Result type: {lib}");
    assert!(
        lib.contains("ValidatorError"),
        "should reference error type: {lib}"
    );
    assert!(
        lib.contains("Ok(__result)"),
        "should wrap result in Ok: {lib}"
    );
}

#[test]
fn contract_without_errors_no_result_type() {
    let project = codegen_ok(
        r#"
contract Simple {
    input  { x: Int }
    output { result: Int }
    requires { x > 0 }
    ensures  { result > 0 }
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        !lib.contains("Result<"),
        "should not use Result without errors: {lib}"
    );
    assert!(
        !lib.contains("thiserror"),
        "should not include thiserror: {lib}"
    );
}

#[test]
fn extract_error_variants_from_raw() {
    let body = Expr::Raw(vec!["DivByZero".into(), ",".into(), "Overflow".into()]);
    let variants = extract_error_variants(&body);
    assert_eq!(variants, vec!["DivByZero", "Overflow"]);
}

#[test]
fn extract_error_variants_from_ident() {
    let body = Expr::Ident("SingleError".into());
    let variants = extract_error_variants(&body);
    assert_eq!(variants, vec!["SingleError"]);
}

#[test]
fn generate_error_enum_output() {
    let mut code = String::new();
    generate_error_enum("Parser", &["BadInput".into(), "TooLong".into()], &mut code);
    assert!(code.contains("pub enum ParserError"));
    assert!(code.contains("BadInput"));
    assert!(code.contains("TooLong"));
    assert!(code.contains("thiserror::Error"));
}

#[test]
fn errors_clause_adds_thiserror_dep() {
    let project = codegen_ok(
        r#"
contract WithErrors {
    input  { x: Int }
    errors { SomeError }
    requires { x > 0 }
}
"#,
    );
    assert!(
        project.cargo_toml.contains("thiserror"),
        "Cargo.toml should include thiserror: {}",
        project.cargo_toml
    );
}

#[test]
fn no_errors_no_thiserror_dep() {
    let project = codegen_ok(
        r#"
contract NoErrors {
    input  { x: Int }
    requires { x > 0 }
}
"#,
    );
    assert!(
        !project.cargo_toml.contains("thiserror"),
        "Cargo.toml should not include thiserror: {}",
        project.cargo_toml
    );
}

// --- WASM target tests ---

fn codegen_wasm(source: &str) -> GeneratedProject {
    let file = assura_parser::parse_unwrap(source);
    let resolved = assura_resolve::resolve(&file).expect("resolve failed");
    let typed = assura_types::type_check(&resolved).expect("type check failed");
    let config = BackendConfig {
        target: CompileTarget::Wasm,
        ..BackendConfig::default()
    };
    codegen_with_config(&typed, &config)
}

#[test]
fn wasm_target_cargo_toml_has_comment() {
    let project = codegen_wasm("");
    assert!(
        project.cargo_toml.contains("wasm32-wasip1"),
        "WASM Cargo.toml should mention wasm32-wasip1: {}",
        project.cargo_toml
    );
}

#[test]
fn native_target_no_wasm_comment() {
    let project = codegen_ok("");
    assert!(
        !project.cargo_toml.contains("wasm32-wasip1"),
        "Native Cargo.toml should not mention wasm32-wasip1"
    );
}

#[test]
fn compile_target_from_str() {
    assert_eq!(
        CompileTarget::from_str_loose("native"),
        Some(CompileTarget::Native)
    );
    assert_eq!(
        CompileTarget::from_str_loose("wasm"),
        Some(CompileTarget::Wasm)
    );
    assert_eq!(
        CompileTarget::from_str_loose("wasm32-wasi"),
        Some(CompileTarget::Wasm)
    );
    assert_eq!(
        CompileTarget::from_str_loose("wasm32-wasip1"),
        Some(CompileTarget::Wasm)
    );
    assert_eq!(CompileTarget::from_str_loose("unknown"), None);
}

#[test]
fn compile_target_rust_target() {
    assert_eq!(CompileTarget::Native.rust_target(), None);
    assert_eq!(CompileTarget::Wasm.rust_target(), Some("wasm32-wasip1"));
}

// --- Bind codegen tests ---

#[test]
fn bind_generates_checked_wrapper() {
    let project = codegen_ok(
        r#"
bind "std::cmp::max" as safe_max {
    input(a: Int, b: Int)
    output(result: Int)
    requires a >= 0
    ensures result >= a
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("fn safe_max"),
        "should generate safe_max fn: {lib}"
    );
    assert!(
        lib.contains("std::cmp::max("),
        "should call the bound Rust function: {lib}"
    );
    assert!(
        lib.contains("debug_assert!"),
        "should have contract assertions: {lib}"
    );
}

#[test]
fn bind_with_requires_and_ensures() {
    let project = codegen_ok(
        r#"
bind "my_crate::divide" as safe_divide {
    input(a: Int, b: Int)
    output(result: Int)
    requires b != 0
    ensures result * b == a
}
"#,
    );
    let lib = &project.files[0].1;
    assert!(
        lib.contains("fn safe_divide"),
        "should generate safe_divide fn: {lib}"
    );
    assert!(
        lib.contains("my_crate::divide("),
        "should call the bound Rust function: {lib}"
    );
}

#[test]
fn collect_type_refs_from_nested_exprs() {
    use assura_parser::ast::*;
    let mut out = std::collections::HashSet::new();

    // Type ref inside a Match arm body
    let expr = Expr::Match {
        scrutinee: Box::new(Expr::Ident("x".into())),
        arms: vec![MatchArm {
            pattern: Pattern::Wildcard,
            body: Expr::Call {
                func: Box::new(Expr::Ident("MyType".into())),
                args: vec![],
            },
        }],
    };
    collect_type_refs_from_expr(&expr, &mut out);
    assert!(
        out.contains("MyType"),
        "should find type ref in Match arm body, got: {out:?}"
    );

    // Type ref inside a Let body
    out.clear();
    let expr = Expr::Let {
        name: "x".into(),
        value: Box::new(Expr::Literal(Literal::Int("1".into()))),
        body: Box::new(Expr::Ident("SomeType".into())),
    };
    collect_type_refs_from_expr(&expr, &mut out);
    assert!(
        out.contains("SomeType"),
        "should find type ref in Let body, got: {out:?}"
    );

    // Type ref inside a Tuple
    out.clear();
    let expr = Expr::Tuple(vec![
        Expr::Ident("x".into()),
        Expr::Ident("CustomStruct".into()),
    ]);
    collect_type_refs_from_expr(&expr, &mut out);
    assert!(
        out.contains("CustomStruct"),
        "should find type ref in Tuple, got: {out:?}"
    );
}

#[test]
fn feature_max_missing_value_emits_compile_error() {
    // A feature_max referenced but with no extractable value should
    // produce compile_error! in the generated code, not a silent "0".
    let source = r#"
feature_max UNKNOWN_CONST

contract UseConst {
    input(x: Int)
    requires { x <= UNKNOWN_CONST }
}
"#;
    let code = codegen_ok(source);
    let lib = &code.files[0].1;
    assert!(
        lib.contains("compile_error!"),
        "missing feature_max value should produce compile_error!, got:\n{lib}"
    );
}

// -------------------------------------------------------------------
// Issue #54: catch-all wildcard elimination tests
// -------------------------------------------------------------------

#[test]
fn extract_output_type_recurses_into_call_args() {
    // Previously a Tuple arg inside Call was silently skipped via _ => {}
    let body = Expr::Call {
        func: Box::new(Expr::Ident("output".into())),
        args: vec![Expr::Tuple(vec![Expr::Cast {
            expr: Box::new(Expr::Ident("x".into())),
            ty: "Int".into(),
        }])],
    };
    let ty = extract_output_type(&body);
    assert_eq!(ty, "i64", "should recurse into Tuple inside Call args");
}

#[test]
fn extract_error_variants_from_block() {
    // Previously Block fell through to _ => vec![]
    let body = Expr::Block(vec![Expr::Ident("ErrA".into()), Expr::Ident("ErrB".into())]);
    let variants = extract_error_variants(&body);
    assert_eq!(variants, vec!["ErrA", "ErrB"]);
}

#[test]
fn extract_error_variants_from_list() {
    let body = Expr::List(vec![Expr::Ident("X".into()), Expr::Ident("Y".into())]);
    let variants = extract_error_variants(&body);
    assert_eq!(variants, vec!["X", "Y"]);
}

#[test]
fn extract_error_variants_from_paren() {
    let body = Expr::Paren(Box::new(Expr::Ident("Wrapped".into())));
    let variants = extract_error_variants(&body);
    assert_eq!(variants, vec!["Wrapped"]);
}

#[test]
fn extract_error_variants_non_ident_returns_empty() {
    // BinOp cannot contain error variant names
    let body = Expr::BinOp {
        lhs: Box::new(Expr::Ident("a".into())),
        op: assura_parser::ast::BinOp::Add,
        rhs: Box::new(Expr::Ident("b".into())),
    };
    let variants = extract_error_variants(&body);
    assert!(variants.is_empty());
}

#[test]
fn generate_trait_method_unsupported_emits_compile_error() {
    // Previously unsupported Expr variants got a silent comment
    let body = Expr::Literal(assura_parser::ast::Literal::Int("42".into()));
    let mut code = String::new();
    generate_trait_method(&body, &mut code);
    assert!(
        code.contains("compile_error!"),
        "unsupported trait method body should emit compile_error!, got:\n{code}"
    );
}

#[test]
fn generate_block_effects_clause_explicit() {
    // Previously Effects fell through to _ => debug comment
    let clauses = vec![Clause {
        kind: ClauseKind::Effects,
        body: Expr::Raw(vec!["io".into()]),
        effect_variables: vec![],
    }];
    let mut code = String::new();
    generate_block(&BlockKind::Feature, "test", &clauses, &mut code);
    assert!(
        code.contains("/// Effects:"),
        "Effects clause should produce doc comment, got:\n{code}"
    );
}

// -----------------------------------------------------------------
// G007: resolve_ordering_variant + codegen Ordering constant
// -----------------------------------------------------------------

#[test]
fn resolve_ordering_acquire() {
    let body = Expr::Ident("acquire".into());
    assert_eq!(resolve_ordering_variant(&body), Some("Acquire"));
}

#[test]
fn resolve_ordering_seq_cst() {
    let body = Expr::Ident("seq_cst".into());
    assert_eq!(resolve_ordering_variant(&body), Some("SeqCst"));
}

#[test]
fn resolve_ordering_raw_tokens() {
    let body = Expr::Raw(vec!["release".into()]);
    assert_eq!(resolve_ordering_variant(&body), Some("Release"));
}

#[test]
fn resolve_ordering_unknown() {
    let body = Expr::Ident("bogus".into());
    assert_eq!(resolve_ordering_variant(&body), None);
}

#[test]
fn codegen_ordering_constant_in_block() {
    let clauses = vec![Clause {
        kind: ClauseKind::Ordering,
        body: Expr::Ident("acquire".into()),
        effect_variables: vec![],
    }];
    let mut code = String::new();
    generate_block(&BlockKind::Feature, "test", &clauses, &mut code);
    assert!(
        code.contains("std::sync::atomic::Ordering::Acquire"),
        "ordering clause should emit Ordering constant, got:\n{code}"
    );
}

#[test]
fn codegen_codec_registry_dispatch() {
    use assura_parser::ast::CodecEntry;
    let cr = CodecRegistryDecl {
        name: "ImageFormats".into(),
        output_type: vec!["ImageOutput".into()],
        codecs: vec![
            CodecEntry {
                name: "Png".into(),
                magic: MagicPattern::Bytes {
                    bytes: vec![0x89, 0x50, 0x4E, 0x47],
                    prefix: false,
                },
                decoder: "decode_png".into(),
                contracts: vec![],
            },
            CodecEntry {
                name: "Bmp".into(),
                magic: MagicPattern::Bytes {
                    bytes: vec![0x42, 0x4D],
                    prefix: true,
                },
                decoder: "decode_bmp".into(),
                contracts: vec![],
            },
        ],
    };
    let mut code = String::new();
    generate_codec_registry(&cr, &mut code);
    assert!(
        code.contains("pub fn dispatch_imageformats"),
        "should generate dispatch function, got:\n{code}"
    );
    assert!(
        code.contains("decode_png(data)"),
        "should call decode_png, got:\n{code}"
    );
    assert!(
        code.contains("decode_bmp(data)"),
        "should call decode_bmp, got:\n{code}"
    );
    assert!(
        code.contains("0x89"),
        "should check magic bytes, got:\n{code}"
    );
}

#[test]
fn codegen_codec_registry_probe() {
    use assura_parser::ast::CodecEntry;
    let cr = CodecRegistryDecl {
        name: "Probed".into(),
        output_type: vec!["Out".into()],
        codecs: vec![CodecEntry {
            name: "Hdr".into(),
            magic: MagicPattern::Probe("is_hdr_format".into()),
            decoder: "decode_hdr".into(),
            contracts: vec![],
        }],
    };
    let mut code = String::new();
    generate_codec_registry(&cr, &mut code);
    assert!(
        code.contains("is_hdr_format(data)"),
        "should call probe function, got:\n{code}"
    );
}

#[test]
fn multi_file_includes_codec_registry() {
    // In multi-file mode, CodecRegistry should generate into shared lib.rs
    let project = codegen_ok(
        r#"
contract Guard {
    input(x: Int)
    requires { x >= 0 }
}

contract Shield {
    input(y: Int)
    ensures { result > 0 }
}

codec_registry ImageFormats {
    output: ImageOutput,
    codec Png {
        magic: [0x89, 0x50, 0x4E, 0x47]
        decoder: decode_png
    }
    codec Jpeg {
        magic: [0xFF, 0xD8]
        decoder: decode_jpeg
    }
}
"#,
    );
    // 2 contracts -> multi-file mode (lib.rs + 2 contract files)
    assert!(project.files.len() >= 3, "expected multi-file output");

    let lib_rs = project
        .files
        .iter()
        .find(|(p, _)| p == "src/lib.rs")
        .expect("missing src/lib.rs");
    assert!(
        lib_rs.1.contains("dispatch_imageformats") || lib_rs.1.contains("decode_png"),
        "lib.rs should contain codec registry dispatch, got:\n{}",
        &lib_rs.1[..lib_rs.1.len().min(500)]
    );
}
