//! Rust code generation from type-checked Assura contracts.
//!
//! Takes a `TypedFile` from `assura-types` and generates a Rust project
//! consisting of a `Cargo.toml` and one or more `.rs` source files.
//! Generated Rust is formatted via `prettyplease`.
//!
//! This is T019: the initial scaffolding. Type mapping (T020), contract
//! codegen (T021), project generation (T022), and struct/enum codegen
//! (T023) extend this foundation.

use assura_parser::ast::{
    BinOp, Clause, ClauseKind, ContractDecl, Decl, EnumDef, Expr, ExternDecl, FnDef, Literal,
    ServiceDecl, ServiceItem, TypeBody, TypeDef, UnaryOp,
};
use assura_types::TypedFile;

// ---------------------------------------------------------------------------
// Public output types
// ---------------------------------------------------------------------------

/// The result of code generation: a complete Rust project.
#[derive(Debug, Clone)]
pub struct GeneratedProject {
    /// Content of the generated `Cargo.toml`.
    pub cargo_toml: String,
    /// Generated source files as `(relative_path, rust_source)` pairs.
    /// Typically `[("src/lib.rs", "...")]`.
    pub files: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/// Generate a Rust project from a type-checked Assura file.
///
/// Walks the AST, maps Assura declarations to Rust source code, and
/// formats the result with `prettyplease`. Returns a `GeneratedProject`
/// with a `Cargo.toml` and generated `.rs` files.
pub fn codegen(typed: &TypedFile) -> GeneratedProject {
    let source = &typed.resolved.source;

    let project_name = source
        .project
        .as_ref()
        .map(|p| p.name.clone())
        .unwrap_or_else(|| "generated".to_string());

    // Sanitize project name for Cargo (replace non-alphanumeric with _)
    let crate_name: String = project_name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect();

    let cargo_toml = generate_cargo_toml(&crate_name);

    let mut code = String::new();

    // Inner module attribute (prettyplease preserves attributes)
    code.push_str("#![allow(dead_code, unused_variables)]\n\n");

    // Collect all generated items
    for decl in &source.decls {
        match &decl.node {
            Decl::TypeDef(t) => generate_type_def(t, &mut code),
            Decl::EnumDef(e) => generate_enum_def(e, &mut code),
            Decl::Contract(c) => generate_contract(c, &mut code),
            Decl::Extern(ex) => generate_extern(ex, &mut code),
            Decl::FnDef(f) => generate_fn_def(f, &mut code),
            Decl::Service(s) => generate_service(s, &mut code),
            Decl::Block { kind, name, body } => {
                generate_block(kind, name, body, &mut code);
            }
        }
    }

    // Format generated Rust via prettyplease, then prepend header comment
    let formatted_body = format_rust(&code);
    let formatted = format!(
        "// Generated by the Assura compiler.\n// Do not edit manually.\n\n{formatted_body}"
    );

    GeneratedProject {
        cargo_toml,
        files: vec![("src/lib.rs".to_string(), formatted)],
    }
}

// ---------------------------------------------------------------------------
// Cargo.toml generation
// ---------------------------------------------------------------------------

fn generate_cargo_toml(crate_name: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

# Generated by the Assura compiler.
# Do not edit manually.

[dependencies]
"#
    )
}

// ---------------------------------------------------------------------------
// Type mapping: Assura types -> Rust types
// ---------------------------------------------------------------------------

/// Map a single Assura type token to its Rust equivalent.
fn map_type_token(tok: &str) -> &str {
    match tok {
        "Int" => "i64",
        "Nat" => "u64",
        "Float" => "f64",
        "Bool" => "bool",
        "String" => "String",
        "Bytes" => "Vec<u8>",
        "Unit" => "()",
        "Never" => "!",
        "U8" => "u8",
        "U16" => "u16",
        "U32" => "u32",
        "U64" => "u64",
        "I8" => "i8",
        "I16" => "i16",
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "List" => "Vec",
        "Map" => "std::collections::BTreeMap",
        "Set" => "std::collections::BTreeSet",
        "Sequence" => "Vec",
        // Option, Result map to themselves
        _ => tok,
    }
}

/// Convert an Assura type token sequence (e.g., `["List", "<", "Int", ">"]`)
/// to a Rust type string.
fn map_type_tokens(tokens: &[String]) -> String {
    if tokens.is_empty() {
        return "()".to_string();
    }

    let mapped: Vec<&str> = tokens.iter().map(|t| map_type_token(t)).collect();
    mapped.join(" ")
}

// ---------------------------------------------------------------------------
// Expression codegen
// ---------------------------------------------------------------------------

/// Convert an Assura `Expr` to a Rust expression string.
fn expr_to_rust(expr: &Expr) -> String {
    match expr {
        Expr::Literal(lit) => match lit {
            Literal::Int(s) | Literal::Float(s) => s.clone(),
            Literal::Str(s) => format!("\"{s}\""),
            Literal::Bool(b) => b.to_string(),
        },
        Expr::Ident(s) => {
            if s == "result" {
                "__result".to_string()
            } else {
                s.clone()
            }
        }
        Expr::Field(recv, field) => format!("{}.{field}", expr_to_rust(recv)),
        Expr::MethodCall {
            receiver,
            method,
            args,
        } => {
            let args_s: Vec<String> = args.iter().map(expr_to_rust).collect();
            format!("{}.{method}({})", expr_to_rust(receiver), args_s.join(", "))
        }
        Expr::Call { func, args } => {
            let args_s: Vec<String> = args.iter().map(expr_to_rust).collect();
            format!("{}({})", expr_to_rust(func), args_s.join(", "))
        }
        Expr::Index { expr: e, index } => {
            format!("{}[{}]", expr_to_rust(e), expr_to_rust(index))
        }
        Expr::BinOp { lhs, op, rhs } => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Lte => "<=",
                BinOp::Gt => ">",
                BinOp::Gte => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Implies => "||", // P => Q  ~  !P || Q (simplified)
                BinOp::In => "/* in */==",
                BinOp::NotIn => "/* not in */!=",
                BinOp::Concat => "/* ++ */+",
                BinOp::Range => "..",
            };
            format!("({} {op_s} {})", expr_to_rust(lhs), expr_to_rust(rhs))
        }
        Expr::UnaryOp { op, expr: e } => {
            let op_s = match op {
                UnaryOp::Neg => "-",
                UnaryOp::Not => "!",
            };
            format!("({op_s}{})", expr_to_rust(e))
        }
        Expr::Old(e) => {
            // old(x) becomes __old_x as a placeholder; proper handling in T021
            format!("/* old */ {}", expr_to_rust(e))
        }
        Expr::Forall { var, domain, body } => {
            format!(
                "{}.iter().all(|{var}| {})",
                expr_to_rust(domain),
                expr_to_rust(body)
            )
        }
        Expr::Exists { var, domain, body } => {
            format!(
                "{}.iter().any(|{var}| {})",
                expr_to_rust(domain),
                expr_to_rust(body)
            )
        }
        Expr::If {
            cond,
            then_branch,
            else_branch,
        } => match else_branch {
            Some(eb) => format!(
                "if {} {{ {} }} else {{ {} }}",
                expr_to_rust(cond),
                expr_to_rust(then_branch),
                expr_to_rust(eb)
            ),
            None => format!(
                "if {} {{ {} }}",
                expr_to_rust(cond),
                expr_to_rust(then_branch)
            ),
        },
        Expr::Paren(e) => format!("({})", expr_to_rust(e)),
        Expr::List(items) => {
            let elems: Vec<String> = items.iter().map(expr_to_rust).collect();
            format!("vec![{}]", elems.join(", "))
        }
        Expr::Cast { expr: e, ty } => {
            format!("({} as {})", expr_to_rust(e), map_type_token(ty))
        }
        Expr::Block(exprs) => {
            let strs: Vec<String> = exprs.iter().map(expr_to_rust).collect();
            strs.join(" ")
        }
        Expr::Raw(tokens) => tokens.join(" "),
    }
}

// ---------------------------------------------------------------------------
// Type definitions
// ---------------------------------------------------------------------------

fn generate_type_def(t: &TypeDef, code: &mut String) {
    let tps = if t.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", t.type_params.join(", "))
    };

    match &t.body {
        TypeBody::Struct(fields) => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps} {{\n",
                t.name
            ));
            for f in fields {
                let vis = if f.is_pub { "pub " } else { "" };
                let ty = map_type_tokens(&f.ty);
                code.push_str(&format!("    {vis}{}: {ty},\n", f.name));
            }
            code.push_str("}\n\n");
        }
        TypeBody::Alias(tokens) => {
            let ty = map_type_tokens(tokens);
            code.push_str(&format!("pub type {}{tps} = {ty};\n\n", t.name));
        }
        TypeBody::Refined(tokens) => {
            // Refined type -> newtype wrapper. The predicate becomes a
            // debug_assert in the constructor (T021 will improve this).
            // For now, just generate a tuple struct wrapping the first
            // identifiable base type.
            let base_ty = extract_base_type_from_refined(tokens);
            code.push_str(&format!(
                "/// Refined type: {}\n#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps}(pub {base_ty});\n\n",
                tokens.join(" "),
                t.name
            ));
        }
        TypeBody::Empty => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps};\n\n",
                t.name
            ));
        }
    }
}

/// Extract the base type from a refined type token sequence like
/// `["n", ":", "Int", "|", "n", ">", "0"]` -> "i64".
fn extract_base_type_from_refined(tokens: &[String]) -> String {
    // Look for a token after ':' that starts with uppercase
    let mut after_colon = false;
    for tok in tokens {
        if tok == ":" {
            after_colon = true;
            continue;
        }
        if after_colon {
            if tok.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
                return map_type_token(tok).to_string();
            }
            // Not a type, stop looking
            after_colon = false;
        }
    }
    // Fallback: just use the first type-looking token
    for tok in tokens {
        if tok.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
            return map_type_token(tok).to_string();
        }
    }
    "i64".to_string()
}

// ---------------------------------------------------------------------------
// Enum definitions
// ---------------------------------------------------------------------------

fn generate_enum_def(e: &EnumDef, code: &mut String) {
    let tps = if e.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", e.type_params.join(", "))
    };

    code.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub enum {}{tps} {{\n",
        e.name
    ));
    for v in &e.variants {
        if v.fields.is_empty() {
            code.push_str(&format!("    {},\n", v.name));
        } else {
            let fields: Vec<String> = v
                .fields
                .iter()
                .map(|f| map_type_token(f).to_string())
                .collect();
            code.push_str(&format!("    {}({}),\n", v.name, fields.join(", ")));
        }
    }
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Contract declarations
// ---------------------------------------------------------------------------

fn generate_contract(c: &ContractDecl, code: &mut String) {
    let tps = if c.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", c.type_params.join(", "))
    };

    code.push_str(&format!(
        "/// Contract: {}\npub mod contract_{} {{\n",
        c.name,
        c.name.to_lowercase()
    ));

    // Extract input params and output type from clauses
    let mut input_params: Vec<(String, String)> = Vec::new();
    let mut output_type = "()".to_string();
    let mut requires_exprs: Vec<String> = Vec::new();
    let mut ensures_exprs: Vec<String> = Vec::new();

    for clause in &c.clauses {
        match &clause.kind {
            ClauseKind::Input => {
                extract_input_params(&clause.body, &mut input_params);
            }
            ClauseKind::Output => {
                output_type = extract_output_type(&clause.body);
            }
            ClauseKind::Requires => {
                requires_exprs.push(expr_to_rust(&clause.body));
            }
            ClauseKind::Ensures => {
                ensures_exprs.push(expr_to_rust(&clause.body));
            }
            _ => {}
        }
    }

    // Generate the contract function signature
    let params_s: String = input_params
        .iter()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .collect::<Vec<_>>()
        .join(", ");

    code.push_str(&format!(
        "    pub fn check{tps}({params_s}) -> {output_type} {{\n"
    ));

    // Generate requires assertions
    for req in &requires_exprs {
        code.push_str(&format!(
            "        debug_assert!({req}, \"requires: {}\");\n",
            req.replace('"', "\\\"")
        ));
    }

    code.push_str(&format!(
        "        let __result: {output_type} = todo!(\"implementation provided by AI agent\");\n"
    ));

    // Generate ensures assertions
    for ens in &ensures_exprs {
        code.push_str(&format!(
            "        debug_assert!({ens}, \"ensures: {}\");\n",
            ens.replace('"', "\\\"")
        ));
    }

    code.push_str("        __result\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
}

/// Extract `(name, rust_type)` pairs from an input clause body.
///
/// Input clauses look like `input(a: Int, b: Int)` which parses as a
/// `Call { func: Ident("input"), args: [...] }` or just identifiers.
fn extract_input_params(body: &Expr, params: &mut Vec<(String, String)>) {
    match body {
        Expr::Call { args, .. } => {
            for arg in args {
                extract_param_from_expr(arg, params);
            }
        }
        Expr::Raw(tokens) => {
            // Try to parse "name: Type" pairs from raw tokens
            let mut i = 0;
            while i + 2 < tokens.len() {
                if tokens.get(i + 1).map(|s| s.as_str()) == Some(":") {
                    let name = tokens[i].clone();
                    let ty = map_type_token(&tokens[i + 2]).to_string();
                    params.push((name, ty));
                    i += 3;
                    // Skip comma
                    if tokens.get(i).map(|s| s.as_str()) == Some(",") {
                        i += 1;
                    }
                } else {
                    i += 1;
                }
            }
        }
        _ => {
            // Single identifier or expression; skip
        }
    }
}

fn extract_param_from_expr(expr: &Expr, params: &mut Vec<(String, String)>) {
    // This handles the case where the parser produced `Ident("a")` etc.
    if let Expr::Ident(name) = expr {
        params.push((name.clone(), "i64".to_string()));
    }
}

/// Extract the Rust return type from an output clause body.
fn extract_output_type(body: &Expr) -> String {
    match body {
        Expr::Call { args, .. } => {
            if args.len() == 1
                && let Expr::Ident(name) = &args[0]
            {
                return map_type_token(name).to_string();
            }
            "()".to_string()
        }
        Expr::Ident(name) => map_type_token(name).to_string(),
        Expr::Raw(tokens) => {
            // Look for the type after ":"
            for (i, tok) in tokens.iter().enumerate() {
                if tok == ":" && i + 1 < tokens.len() {
                    return map_type_token(&tokens[i + 1]).to_string();
                }
            }
            if tokens.len() == 1 {
                return map_type_token(&tokens[0]).to_string();
            }
            "()".to_string()
        }
        _ => "()".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Extern declarations
// ---------------------------------------------------------------------------

fn generate_extern(ex: &ExternDecl, code: &mut String) {
    let params_s: String = ex
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, map_type_tokens(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    let ret = if ex.return_ty.is_empty() {
        "()".to_string()
    } else {
        map_type_tokens(&ex.return_ty)
    };

    // Generate as a regular function with contract assertions
    code.push_str(&format!(
        "/// Extern: {}\npub fn {}({params_s}) -> {ret} {{\n",
        ex.name, ex.name
    ));

    for clause in &ex.clauses {
        match &clause.kind {
            ClauseKind::Requires => {
                let expr = expr_to_rust(&clause.body);
                code.push_str(&format!(
                    "    debug_assert!({expr}, \"requires: {}\");\n",
                    expr.replace('"', "\\\"")
                ));
            }
            ClauseKind::Ensures => {
                // Ensures checked after body; for extern stubs, just emit
                // as a comment since there is no body.
                let expr = expr_to_rust(&clause.body);
                code.push_str(&format!("    // ensures: {expr}\n"));
            }
            _ => {}
        }
    }

    code.push_str("    todo!(\"extern function: implementation required\")\n");
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Function definitions
// ---------------------------------------------------------------------------

fn generate_fn_def(f: &FnDef, code: &mut String) {
    let params_s: String = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, map_type_tokens(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    let ret = if f.return_ty.is_empty() {
        String::new()
    } else {
        format!(" -> {}", map_type_tokens(&f.return_ty))
    };

    code.push_str(&format!("pub fn {}({params_s}){ret} {{\n", f.name));

    for clause in &f.clauses {
        match &clause.kind {
            ClauseKind::Requires => {
                let expr = expr_to_rust(&clause.body);
                code.push_str(&format!(
                    "    debug_assert!({expr}, \"requires: {}\");\n",
                    expr.replace('"', "\\\"")
                ));
            }
            ClauseKind::Ensures => {
                let expr = expr_to_rust(&clause.body);
                code.push_str(&format!("    // ensures: {expr}\n"));
            }
            _ => {}
        }
    }

    code.push_str("    todo!(\"implementation provided by AI agent\")\n");
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Service declarations
// ---------------------------------------------------------------------------

fn generate_service(s: &ServiceDecl, code: &mut String) {
    code.push_str(&format!(
        "/// Service: {}\npub mod {} {{\n",
        s.name,
        s.name.to_lowercase()
    ));

    for item in &s.items {
        match item {
            ServiceItem::TypeDef(t) => {
                let mut inner = String::new();
                generate_type_def(t, &mut inner);
                // Indent inner code
                for line in inner.lines() {
                    code.push_str(&format!("    {line}\n"));
                }
            }
            ServiceItem::EnumDef(e) => {
                let mut inner = String::new();
                generate_enum_def(e, &mut inner);
                for line in inner.lines() {
                    code.push_str(&format!("    {line}\n"));
                }
            }
            ServiceItem::States(states) => {
                // Generate a state enum
                code.push_str("    #[derive(Debug, Clone, PartialEq)]\n");
                code.push_str("    pub enum State {\n");
                for state in states {
                    code.push_str(&format!("        {state},\n"));
                }
                code.push_str("    }\n\n");
            }
            ServiceItem::Operation { name, clauses } => {
                code.push_str(&format!("    /// Operation: {name}\n"));
                code.push_str(&format!("    pub fn {name}() {{\n"));
                for clause in clauses {
                    if clause.kind == ClauseKind::Requires {
                        let expr = expr_to_rust(&clause.body);
                        code.push_str(&format!(
                            "        debug_assert!({expr}, \"requires: {}\");\n",
                            expr.replace('"', "\\\"")
                        ));
                    }
                }
                code.push_str("        todo!(\"operation implementation\")\n");
                code.push_str("    }\n\n");
            }
            ServiceItem::Query { name, clauses } => {
                code.push_str(&format!("    /// Query: {name}\n"));
                code.push_str(&format!("    pub fn {name}() {{\n"));
                for clause in clauses {
                    if clause.kind == ClauseKind::Requires {
                        let expr = expr_to_rust(&clause.body);
                        code.push_str(&format!(
                            "        debug_assert!({expr}, \"requires: {}\");\n",
                            expr.replace('"', "\\\"")
                        ));
                    }
                }
                code.push_str("        todo!(\"query implementation\")\n");
                code.push_str("    }\n\n");
            }
            ServiceItem::Invariant(expr) => {
                let rust_expr = expr_to_rust(expr);
                code.push_str(&format!("    // invariant: {rust_expr}\n\n"));
            }
            ServiceItem::Other { kind, body } => {
                let rust_expr = expr_to_rust(body);
                code.push_str(&format!("    // {kind}: {rust_expr}\n\n"));
            }
        }
    }

    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Generic blocks (feature, incremental, etc.)
// ---------------------------------------------------------------------------

fn generate_block(kind: &str, name: &str, body: &[Clause], code: &mut String) {
    code.push_str(&format!(
        "/// {kind}: {name}\npub mod block_{} {{\n",
        name.to_lowercase()
    ));

    for clause in body {
        let expr = expr_to_rust(&clause.body);
        code.push_str(&format!("    // {:?}: {expr}\n", clause.kind));
    }

    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Rust formatting via prettyplease
// ---------------------------------------------------------------------------

/// Format a Rust source string via prettyplease.
///
/// If parsing fails (the generated code is not valid Rust syntax),
/// returns the input unchanged with a comment noting the failure.
fn format_rust(code: &str) -> String {
    match syn::parse_file(code) {
        Ok(syntax_tree) => prettyplease::unparse(&syntax_tree),
        Err(_e) => {
            // Return unformatted with a note; the code may have syntax
            // issues that T020-T023 will fix as codegen matures.
            format!(
                "// NOTE: prettyplease formatting skipped (parse error in generated code)\n\n{code}"
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: parse + resolve + type-check source text, then codegen.
    fn codegen_ok(source: &str) -> GeneratedProject {
        let (file, errs) = assura_parser::parse(source);
        assert!(errs.is_empty(), "unexpected parse errors: {errs:?}");
        let file = file.expect("parse returned None");
        let resolved = assura_resolve::resolve(&file).expect("resolve failed");
        let typed = assura_types::type_check(&resolved).expect("type check failed");
        codegen(&typed)
    }

    #[test]
    fn empty_file_generates_project() {
        let project = codegen_ok("");
        assert!(!project.cargo_toml.is_empty());
        assert_eq!(project.files.len(), 1);
        assert_eq!(project.files[0].0, "src/lib.rs");
        assert!(
            project.files[0]
                .1
                .contains("Generated by the Assura compiler")
        );
    }

    #[test]
    fn struct_codegen() {
        let project = codegen_ok(
            r#"
type Point {
    x: Int
    y: Int
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("struct Point"), "should contain struct Point");
        assert!(lib.contains("i64"), "should map Int to i64");
    }

    #[test]
    fn enum_codegen() {
        let project = codegen_ok(
            r#"
enum Color {
    Red,
    Green,
    Blue
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("enum Color"), "should contain enum Color");
        assert!(lib.contains("Red"), "should contain Red variant");
        assert!(lib.contains("Green"), "should contain Green variant");
        assert!(lib.contains("Blue"), "should contain Blue variant");
    }

    #[test]
    fn contract_generates_module() {
        let project = codegen_ok(
            r#"
contract SafeDivision {
    requires { true }
    ensures  { true }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("contract_safedivision"),
            "should contain contract module"
        );
    }

    #[test]
    fn fn_def_codegen() {
        // Note: the current parser stores fn clauses in return_ty as raw
        // tokens rather than structured Clause objects. So fn codegen
        // generates the return type string including clause keywords.
        // The codegen still generates a valid function stub.
        let project = codegen_ok(
            r#"
fn helper(n: Int) -> Int {
    requires { n >= 0 }
    ensures  { result >= 0 }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("fn helper"), "should contain fn helper");
    }

    #[test]
    fn contract_generates_debug_assert() {
        let project = codegen_ok(
            r#"
contract Positive {
    requires { true }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("debug_assert!"),
            "contract requires should generate debug_assert"
        );
    }

    #[test]
    fn project_name_used_in_cargo_toml() {
        let project = codegen_ok(
            r#"
project my_cool_project {
    profile: [core]
}

contract Foo {
    requires { true }
}
"#,
        );
        assert!(
            project.cargo_toml.contains("my_cool_project"),
            "Cargo.toml should use the project name"
        );
    }

    #[test]
    fn service_generates_module() {
        let project = codegen_ok(
            r#"
service MyService {
    states: Init -> Running -> Stopped

    operation Start {
        requires: true
    }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("mod myservice"),
            "should contain service module"
        );
        assert!(lib.contains("State"), "should contain state enum");
    }

    #[test]
    fn cargo_toml_well_formed() {
        let project = codegen_ok("");
        assert!(project.cargo_toml.contains("[package]"));
        assert!(project.cargo_toml.contains("edition = \"2024\""));
        assert!(project.cargo_toml.contains("[dependencies]"));
    }
}
