//! Rust code generation from type-checked Assura contracts.
//!
//! Takes a `TypedFile` from `assura-types` and generates a Rust project
//! consisting of a `Cargo.toml` and one or more `.rs` source files.
//! Generated Rust is formatted via `prettyplease`.
//!
//! This is T019: the initial scaffolding. Type mapping (T020), contract
//! codegen (T021), project generation (T022), and struct/enum codegen
//! (T023) extend this foundation.

use assura_parser::ast::{
    BinOp, Clause, ClauseKind, ContractDecl, Decl, EnumDef, Expr, ExternDecl, FnDef, Literal,
    ServiceDecl, ServiceItem, TypeBody, TypeDef, UnaryOp,
};
use assura_types::TypedFile;

// ---------------------------------------------------------------------------
// Public output types
// ---------------------------------------------------------------------------

/// The result of code generation: a complete Rust project.
#[derive(Debug, Clone)]
pub struct GeneratedProject {
    /// Content of the generated `Cargo.toml`.
    pub cargo_toml: String,
    /// Generated source files as `(relative_path, rust_source)` pairs.
    /// Typically `[("src/lib.rs", "...")]`.
    pub files: Vec<(String, String)>,
}

// ---------------------------------------------------------------------------
// T119: Backend selection (Rustc vs Cranelift for fast dev builds)
// ---------------------------------------------------------------------------

/// Code generation backend.
#[derive(Debug, Clone, PartialEq)]
pub enum CodegenBackend {
    /// Standard rustc backend (optimized, production).
    Rustc,
    /// Cranelift backend (fast compilation, dev builds).
    Cranelift,
}

/// Configuration for code generation.
#[derive(Debug, Clone)]
pub struct BackendConfig {
    pub backend: CodegenBackend,
    pub opt_level: u8,
    pub debug_info: bool,
}

impl Default for BackendConfig {
    fn default() -> Self {
        Self {
            backend: CodegenBackend::Rustc,
            opt_level: 2,
            debug_info: false,
        }
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/// Generate a Rust project from a type-checked Assura file.
///
/// Walks the AST, maps Assura declarations to Rust source code, and
/// formats the result with `prettyplease`. Returns a `GeneratedProject`
/// with a `Cargo.toml` and generated `.rs` files.
pub fn codegen_with_config(typed: &TypedFile, config: &BackendConfig) -> GeneratedProject {
    let _ = config; // T119: backend selection will influence Cargo.toml and build flags
    codegen(typed)
}

/// Generate a Rust project from a type-checked Assura file.
///
/// Uses default backend configuration (`Rustc`, opt-level 2, no debug info).
/// For custom configuration, use [`codegen_with_config`].
pub fn codegen(typed: &TypedFile) -> GeneratedProject {
    let source = &typed.resolved.source;

    let project_name = source
        .project
        .as_ref()
        .map(|p| p.name.clone())
        .unwrap_or_else(|| "generated".to_string());

    // Sanitize project name for Cargo (replace non-alphanumeric with _)
    let crate_name: String = project_name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect();

    let cargo_toml = generate_cargo_toml(&crate_name);

    let mut code = String::new();

    // Inner module attribute (prettyplease preserves attributes)
    code.push_str("#![allow(dead_code, unused_variables)]\n\n");

    // Collect all generated items
    for decl in &source.decls {
        match &decl.node {
            Decl::TypeDef(t) => generate_type_def(t, &mut code),
            Decl::EnumDef(e) => generate_enum_def(e, &mut code),
            Decl::Contract(c) => generate_contract(c, &mut code),
            Decl::Extern(ex) => generate_extern(ex, &mut code),
            Decl::FnDef(f) => {
                // T043 CORE.1: ghost functions are erased at runtime
                // T044 CORE.2: lemma functions are erased at runtime
                if !f.is_ghost && !f.is_lemma {
                    generate_fn_def(f, &mut code);
                }
            }
            Decl::Service(s) => generate_service(s, &mut code),
            Decl::Block { kind, name, body } => {
                generate_block(kind, name, body, &mut code);
            }
        }
    }

    // Format generated Rust via prettyplease, then prepend header comment
    let formatted_body = format_rust(&code);
    let formatted = format!(
        "// Generated by the Assura compiler.\n// Do not edit manually.\n\n{formatted_body}"
    );

    GeneratedProject {
        cargo_toml,
        files: vec![("src/lib.rs".to_string(), formatted)],
    }
}

// ---------------------------------------------------------------------------
// Cargo.toml generation
// ---------------------------------------------------------------------------

fn generate_cargo_toml(crate_name: &str) -> String {
    format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

# Generated by the Assura compiler.
# Do not edit manually.

[dependencies]
"#
    )
}

// ---------------------------------------------------------------------------
// Type mapping: Assura types -> Rust types
// ---------------------------------------------------------------------------

/// Map a single Assura type token to its Rust equivalent.
fn map_type_token(tok: &str) -> &str {
    match tok {
        "Int" => "i64",
        "Nat" => "u64",
        "Float" => "f64",
        "Bool" => "bool",
        "String" => "String",
        "Bytes" => "Vec<u8>",
        "Unit" => "()",
        "Never" => "!",
        "U8" => "u8",
        "U16" => "u16",
        "U32" => "u32",
        "U64" => "u64",
        "I8" => "i8",
        "I16" => "i16",
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "List" => "Vec",
        "Map" => "std::collections::BTreeMap",
        "Set" => "std::collections::BTreeSet",
        "Sequence" => "Vec",
        // Option, Result map to themselves
        _ => tok,
    }
}

/// Convert an Assura type token sequence (e.g., `["List", "<", "Int", ">"]`)
/// to a valid Rust type string.
///
/// Handles Assura-specific syntax that is not valid Rust:
/// - Refinement types: `{ x : T | P }` -> base type `T`
/// - Taint annotations: `T @ taint : label` -> just `T`
/// - Union error types: `T | E` -> `Result<T, E>`
/// - Smart joining: `Vec < i64 >` -> `Vec<i64>`
fn map_type_tokens(tokens: &[String]) -> String {
    if tokens.is_empty() {
        return "()".to_string();
    }

    // Phase 1: Strip taint annotations (everything from "@" onward)
    let clean: Vec<&str> = tokens
        .iter()
        .map(|s| s.as_str())
        .take_while(|t| *t != "@")
        .collect();
    if clean.is_empty() {
        return "()".to_string();
    }

    // Phase 2: Strip refinement predicates: { x : T | P } -> just the base type
    if clean.first() == Some(&"{") {
        return extract_base_type_from_refined(tokens);
    }

    // Phase 3: Handle union error types: T | E -> Result<T, E>
    // Find a "|" not inside angle brackets
    let mut depth = 0i32;
    let mut pipe_pos = None;
    for (i, tok) in clean.iter().enumerate() {
        match *tok {
            "<" => depth += 1,
            ">" => {
                if depth > 0 {
                    depth -= 1;
                }
            }
            "|" if depth == 0 => {
                pipe_pos = Some(i);
                break;
            }
            _ => {}
        }
    }

    if let Some(pos) = pipe_pos {
        let ok_tokens: Vec<String> = clean[..pos].iter().map(|s| s.to_string()).collect();
        let err_tokens: Vec<String> = clean[pos + 1..].iter().map(|s| s.to_string()).collect();
        let ok_type = map_type_tokens(&ok_tokens);
        let err_type = map_type_tokens(&err_tokens);
        return format!("Result<{ok_type}, {err_type}>");
    }

    // Phase 4: Map each token and join smartly (no extra spaces around < > & etc.)
    let mapped: Vec<&str> = clean.iter().map(|t| map_type_token(t)).collect();
    smart_join_type_tokens(&mapped)
}

/// Join type tokens without spurious spaces around angle brackets, ampersands, etc.
fn smart_join_type_tokens(tokens: &[&str]) -> String {
    let mut result = String::new();
    for (i, tok) in tokens.iter().enumerate() {
        if i > 0 {
            let prev = tokens[i - 1];
            let no_space = matches!(*tok, ">" | "," | ")" | ".")
                || matches!(prev, "<" | "(" | "&" | ".")
                || (*tok == "mut" && prev == "&");
            if !no_space {
                result.push(' ');
            }
        }
        result.push_str(tok);
    }
    result
}

// ---------------------------------------------------------------------------
// Expression codegen
// ---------------------------------------------------------------------------

/// Convert an Assura `Expr` to a Rust expression string.
fn expr_to_rust(expr: &Expr) -> String {
    match expr {
        Expr::Literal(lit) => match lit {
            Literal::Int(s) | Literal::Float(s) => s.clone(),
            Literal::Str(s) => format!("\"{s}\""),
            Literal::Bool(b) => b.to_string(),
        },
        Expr::Ident(s) => {
            if s == "result" {
                "__result".to_string()
            } else {
                s.clone()
            }
        }
        Expr::Field(recv, field) => format!("{}.{field}", expr_to_rust(recv)),
        Expr::MethodCall {
            receiver,
            method,
            args,
        } => {
            let args_s: Vec<String> = args.iter().map(expr_to_rust).collect();
            format!("{}.{method}({})", expr_to_rust(receiver), args_s.join(", "))
        }
        Expr::Call { func, args } => {
            let args_s: Vec<String> = args.iter().map(expr_to_rust).collect();
            format!("{}({})", expr_to_rust(func), args_s.join(", "))
        }
        Expr::Index { expr: e, index } => {
            format!("{}[{}]", expr_to_rust(e), expr_to_rust(index))
        }
        Expr::BinOp { lhs, op, rhs } => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Lte => "<=",
                BinOp::Gt => ">",
                BinOp::Gte => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Implies => {
                    return format!("(!{} || {})", expr_to_rust(lhs), expr_to_rust(rhs));
                }
                BinOp::In => {
                    return format!("{}.contains(&{})", expr_to_rust(lhs), expr_to_rust(rhs));
                }
                BinOp::NotIn => {
                    return format!("!{}.contains(&{})", expr_to_rust(lhs), expr_to_rust(rhs));
                }
                BinOp::Concat => {
                    return format!("[{}, {}].concat()", expr_to_rust(lhs), expr_to_rust(rhs));
                }
                BinOp::Range => "..",
            };
            format!("({} {op_s} {})", expr_to_rust(lhs), expr_to_rust(rhs))
        }
        Expr::UnaryOp { op, expr: e } => {
            let op_s = match op {
                UnaryOp::Neg => "-",
                UnaryOp::Not => "!",
            };
            format!("({op_s}{})", expr_to_rust(e))
        }
        Expr::Old(e) => {
            // old(expr) references a pre-state snapshot saved at function entry.
            // The variable name is derived from the inner expression.
            format!("__old_{}", old_var_name(e))
        }
        Expr::Forall { var, domain, body } => {
            format!(
                "{}.iter().all(|{var}| {})",
                expr_to_rust(domain),
                expr_to_rust(body)
            )
        }
        Expr::Exists { var, domain, body } => {
            format!(
                "{}.iter().any(|{var}| {})",
                expr_to_rust(domain),
                expr_to_rust(body)
            )
        }
        Expr::If {
            cond,
            then_branch,
            else_branch,
        } => match else_branch {
            Some(eb) => format!(
                "if {} {{ {} }} else {{ {} }}",
                expr_to_rust(cond),
                expr_to_rust(then_branch),
                expr_to_rust(eb)
            ),
            None => format!(
                "if {} {{ {} }}",
                expr_to_rust(cond),
                expr_to_rust(then_branch)
            ),
        },
        Expr::Paren(e) => format!("({})", expr_to_rust(e)),
        Expr::List(items) => {
            let elems: Vec<String> = items.iter().map(expr_to_rust).collect();
            format!("vec![{}]", elems.join(", "))
        }
        Expr::Cast { expr: e, ty } => {
            format!("({} as {})", expr_to_rust(e), map_type_token(ty))
        }
        Expr::Block(exprs) => {
            let strs: Vec<String> = exprs.iter().map(expr_to_rust).collect();
            strs.join(" ")
        }
        Expr::Ghost(_inner) => {
            // Ghost blocks are erased at runtime; emit nothing.
            "/* ghost erased */()".to_string()
        }
        Expr::Apply { lemma_name, .. } => {
            // Lemma applications are erased at runtime; emit comment.
            format!("/* lemma {lemma_name} applied */")
        }
        Expr::Match { scrutinee, arms } => {
            let scrut = expr_to_rust(scrutinee);
            let arms_code: Vec<String> = arms
                .iter()
                .map(|arm| {
                    let pat = match &arm.pattern {
                        assura_parser::ast::Pattern::Ident(name) => name.clone(),
                        assura_parser::ast::Pattern::Wildcard => "_".into(),
                        assura_parser::ast::Pattern::Literal(lit) => match lit {
                            Literal::Int(s) | Literal::Float(s) => s.clone(),
                            Literal::Str(s) => format!("\"{s}\""),
                            Literal::Bool(b) => b.to_string(),
                        },
                        assura_parser::ast::Pattern::Constructor { name, .. } => {
                            format!("{name}(..)")
                        }
                    };
                    let body = expr_to_rust(&arm.body);
                    format!("    {pat} => {body},")
                })
                .collect();
            format!("match {} {{\n{}\n}}", scrut, arms_code.join("\n"))
        }
        Expr::Raw(tokens) => {
            let mapped: Vec<&str> = tokens.iter().map(|t| map_type_token(t)).collect();
            smart_join_type_tokens(&mapped)
        }
    }
}

// ---------------------------------------------------------------------------
// old(expr) support
// ---------------------------------------------------------------------------

/// Derive a variable name for an `old(expr)` snapshot from the expression.
/// E.g., `old(x)` -> `__old_x`, `old(buf.len)` -> `__old_buf_len`.
fn old_var_name(expr: &Expr) -> String {
    match expr {
        Expr::Ident(s) => s.clone(),
        Expr::Field(recv, field) => format!("{}_{field}", old_var_name(recv)),
        Expr::Call { func, .. } => old_var_name(func),
        Expr::MethodCall {
            receiver, method, ..
        } => format!("{}_{method}", old_var_name(receiver)),
        Expr::Index { expr: e, .. } => old_var_name(e),
        _ => "expr".to_string(),
    }
}

/// Walk an expression tree and collect all `old(inner)` sub-expressions.
/// Returns `(var_name, rust_expr)` pairs for generating pre-state snapshots.
fn collect_old_exprs(expr: &Expr) -> Vec<(String, String)> {
    let mut result = Vec::new();
    collect_old_exprs_inner(expr, &mut result);
    result
}

fn collect_old_exprs_inner(expr: &Expr, out: &mut Vec<(String, String)>) {
    match expr {
        Expr::Old(inner) => {
            let var = old_var_name(inner);
            let rust = expr_to_rust(inner);
            // Avoid duplicates
            if !out.iter().any(|(v, _)| v == &var) {
                out.push((var, rust));
            }
            // Also recurse into the inner expression (in case of nested old)
            collect_old_exprs_inner(inner, out);
        }
        Expr::BinOp { lhs, rhs, .. } => {
            collect_old_exprs_inner(lhs, out);
            collect_old_exprs_inner(rhs, out);
        }
        Expr::UnaryOp { expr: e, .. }
        | Expr::Paren(e)
        | Expr::Field(e, _)
        | Expr::Cast { expr: e, .. } => {
            collect_old_exprs_inner(e, out);
        }
        Expr::Call { func, args } => {
            collect_old_exprs_inner(func, out);
            for a in args {
                collect_old_exprs_inner(a, out);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_old_exprs_inner(receiver, out);
            for a in args {
                collect_old_exprs_inner(a, out);
            }
        }
        Expr::Index { expr: e, index } => {
            collect_old_exprs_inner(e, out);
            collect_old_exprs_inner(index, out);
        }
        Expr::Forall { domain, body, .. } | Expr::Exists { domain, body, .. } => {
            collect_old_exprs_inner(domain, out);
            collect_old_exprs_inner(body, out);
        }
        Expr::If {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_old_exprs_inner(cond, out);
            collect_old_exprs_inner(then_branch, out);
            if let Some(eb) = else_branch {
                collect_old_exprs_inner(eb, out);
            }
        }
        Expr::List(items) | Expr::Block(items) => {
            for item in items {
                collect_old_exprs_inner(item, out);
            }
        }
        Expr::Ghost(inner) => {
            // Ghost blocks are erased but may reference old() in
            // their verification expressions.
            collect_old_exprs_inner(inner, out);
        }
        Expr::Apply { args, .. } => {
            // Apply is erased but may reference old() in arguments.
            for a in args {
                collect_old_exprs_inner(a, out);
            }
        }
        Expr::Match { scrutinee, arms } => {
            collect_old_exprs_inner(scrutinee, out);
            for arm in arms {
                collect_old_exprs_inner(&arm.body, out);
            }
        }
        // Leaf nodes: no old() inside
        Expr::Literal(_) | Expr::Ident(_) | Expr::Raw(_) => {}
    }
}

// ---------------------------------------------------------------------------
// Type definitions
// ---------------------------------------------------------------------------

fn generate_type_def(t: &TypeDef, code: &mut String) {
    let tps = if t.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", t.type_params.join(", "))
    };

    match &t.body {
        TypeBody::Struct(fields) => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps} {{\n",
                t.name
            ));
            for f in fields {
                let vis = if f.is_pub { "pub " } else { "" };
                let ty = map_type_tokens(&f.ty);
                code.push_str(&format!("    {vis}{}: {ty},\n", f.name));
            }
            code.push_str("}\n\n");
        }
        TypeBody::Alias(tokens) => {
            let ty = map_type_tokens(tokens);
            code.push_str(&format!("pub type {}{tps} = {ty};\n\n", t.name));
        }
        TypeBody::Refined(tokens) => {
            // Refined type -> newtype wrapper. The predicate becomes a
            // debug_assert in the constructor (T021 will improve this).
            // For now, just generate a tuple struct wrapping the first
            // identifiable base type.
            let base_ty = extract_base_type_from_refined(tokens);
            code.push_str(&format!(
                "/// Refined type: {}\n#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps}(pub {base_ty});\n\n",
                tokens.join(" "),
                t.name
            ));
        }
        TypeBody::Empty => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps};\n\n",
                t.name
            ));
        }
    }
}

/// Extract the base type from a refined type token sequence like
/// `["n", ":", "Int", "|", "n", ">", "0"]` -> "i64".
fn extract_base_type_from_refined(tokens: &[String]) -> String {
    // Look for a token after ':' that starts with uppercase
    let mut after_colon = false;
    for tok in tokens {
        if tok == ":" {
            after_colon = true;
            continue;
        }
        if after_colon {
            if tok.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
                return map_type_token(tok).to_string();
            }
            // Not a type, stop looking
            after_colon = false;
        }
    }
    // Fallback: just use the first type-looking token
    for tok in tokens {
        if tok.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
            return map_type_token(tok).to_string();
        }
    }
    "i64".to_string()
}

// ---------------------------------------------------------------------------
// Enum definitions
// ---------------------------------------------------------------------------

fn generate_enum_def(e: &EnumDef, code: &mut String) {
    let tps = if e.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", e.type_params.join(", "))
    };

    code.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub enum {}{tps} {{\n",
        e.name
    ));
    for v in &e.variants {
        if v.fields.is_empty() {
            code.push_str(&format!("    {},\n", v.name));
        } else {
            let fields: Vec<String> = v
                .fields
                .iter()
                .map(|f| map_type_token(f).to_string())
                .collect();
            code.push_str(&format!("    {}({}),\n", v.name, fields.join(", ")));
        }
    }
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Contract declarations
// ---------------------------------------------------------------------------

fn generate_contract(c: &ContractDecl, code: &mut String) {
    let tps = if c.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", c.type_params.join(", "))
    };

    code.push_str(&format!(
        "/// Contract: {}\npub mod contract_{} {{\n",
        c.name,
        c.name.to_lowercase()
    ));

    // Extract input params and output type from clauses
    let mut input_params: Vec<(String, String)> = Vec::new();
    let mut output_type = "()".to_string();
    let mut requires_exprs: Vec<String> = Vec::new();
    let mut ensures_exprs: Vec<String> = Vec::new();

    for clause in &c.clauses {
        match &clause.kind {
            ClauseKind::Input => {
                extract_input_params(&clause.body, &mut input_params);
            }
            ClauseKind::Output => {
                output_type = extract_output_type(&clause.body);
            }
            ClauseKind::Requires => {
                requires_exprs.push(expr_to_rust(&clause.body));
            }
            ClauseKind::Ensures => {
                ensures_exprs.push(expr_to_rust(&clause.body));
            }
            _ => {}
        }
    }

    // Generate the contract function signature
    let params_s: String = input_params
        .iter()
        .map(|(name, ty)| format!("{name}: {ty}"))
        .collect::<Vec<_>>()
        .join(", ");

    code.push_str(&format!(
        "    pub fn check{tps}({params_s}) -> {output_type} {{\n"
    ));

    // Collect old() expressions from ensures clauses and save pre-state values
    for clause in &c.clauses {
        if clause.kind == ClauseKind::Ensures {
            for (var, rust_expr) in collect_old_exprs(&clause.body) {
                code.push_str(&format!("        let __old_{var} = {rust_expr}.clone();\n"));
            }
        }
    }

    // Generate requires assertions
    for req in &requires_exprs {
        code.push_str(&format!(
            "        debug_assert!({req}, \"requires: {}\");\n",
            req.replace('"', "\\\"")
        ));
    }

    code.push_str(&format!(
        "        let __result: {output_type} = todo!(\"implementation provided by AI agent\");\n"
    ));

    // Generate ensures assertions
    for ens in &ensures_exprs {
        code.push_str(&format!(
            "        debug_assert!({ens}, \"ensures: {}\");\n",
            ens.replace('"', "\\\"")
        ));
    }

    code.push_str("        __result\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
}

/// Extract `(name, rust_type)` pairs from an input clause body.
///
/// Input clauses look like `input(a: Int, b: Int)` which parses as a
/// `Call { func: Ident("input"), args: [...] }` or just identifiers.
fn extract_input_params(body: &Expr, params: &mut Vec<(String, String)>) {
    match body {
        Expr::Call { args, .. } => {
            for arg in args {
                extract_param_from_expr(arg, params);
            }
        }
        Expr::Raw(tokens) => {
            // Try to parse "name: Type" pairs from raw tokens
            let mut i = 0;
            while i + 2 < tokens.len() {
                if tokens.get(i + 1).map(|s| s.as_str()) == Some(":") {
                    let name = tokens[i].clone();
                    let ty = map_type_token(&tokens[i + 2]).to_string();
                    params.push((name, ty));
                    i += 3;
                    // Skip comma
                    if tokens.get(i).map(|s| s.as_str()) == Some(",") {
                        i += 1;
                    }
                } else {
                    i += 1;
                }
            }
        }
        _ => {
            // Single identifier or expression; skip
        }
    }
}

fn extract_param_from_expr(expr: &Expr, params: &mut Vec<(String, String)>) {
    // This handles the case where the parser produced `Ident("a")` etc.
    if let Expr::Ident(name) = expr {
        params.push((name.clone(), "i64".to_string()));
    }
}

/// Extract the Rust return type from an output clause body.
fn extract_output_type(body: &Expr) -> String {
    match body {
        Expr::Call { args, .. } => {
            if args.len() == 1
                && let Expr::Ident(name) = &args[0]
            {
                return map_type_token(name).to_string();
            }
            "()".to_string()
        }
        Expr::Ident(name) => map_type_token(name).to_string(),
        Expr::Raw(tokens) => {
            // Look for the type after ":"
            for (i, tok) in tokens.iter().enumerate() {
                if tok == ":" && i + 1 < tokens.len() {
                    return map_type_token(&tokens[i + 1]).to_string();
                }
            }
            if tokens.len() == 1 {
                return map_type_token(&tokens[0]).to_string();
            }
            "()".to_string()
        }
        _ => "()".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Extern declarations
// ---------------------------------------------------------------------------

fn generate_extern(ex: &ExternDecl, code: &mut String) {
    let params_s: String = ex
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, map_type_tokens(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    let ret = if ex.return_ty.is_empty() {
        "()".to_string()
    } else {
        map_type_tokens(&ex.return_ty)
    };

    // Generate as a regular function with contract assertions
    code.push_str(&format!(
        "/// Extern: {}\npub fn {}({params_s}) -> {ret} {{\n",
        ex.name, ex.name
    ));

    // Collect old() expressions from ensures clauses and save pre-state values
    let mut ensures_exprs: Vec<String> = Vec::new();
    for clause in &ex.clauses {
        if clause.kind == ClauseKind::Ensures {
            for (var, rust_expr) in collect_old_exprs(&clause.body) {
                code.push_str(&format!("    let __old_{var} = {rust_expr}.clone();\n"));
            }
            ensures_exprs.push(expr_to_rust(&clause.body));
        }
    }

    // Generate requires assertions at function entry
    for clause in &ex.clauses {
        if clause.kind == ClauseKind::Requires {
            let expr = expr_to_rust(&clause.body);
            code.push_str(&format!(
                "    debug_assert!({expr}, \"requires: {}\");\n",
                expr.replace('"', "\\\"")
            ));
        }
    }

    code.push_str(&format!(
        "    let __result: {ret} = todo!(\"extern function: implementation required\");\n"
    ));

    // Generate ensures assertions before return
    for ens in &ensures_exprs {
        code.push_str(&format!(
            "    debug_assert!({ens}, \"ensures: {}\");\n",
            ens.replace('"', "\\\"")
        ));
    }

    code.push_str("    __result\n");
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Function definitions
// ---------------------------------------------------------------------------

fn generate_fn_def(f: &FnDef, code: &mut String) {
    let params_s: String = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, map_type_tokens(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    let ret_ty = if f.return_ty.is_empty() {
        "()".to_string()
    } else {
        map_type_tokens(&f.return_ty)
    };

    let ret_sig = if f.return_ty.is_empty() {
        String::new()
    } else {
        format!(" -> {ret_ty}")
    };

    code.push_str(&format!("pub fn {}({params_s}){ret_sig} {{\n", f.name));

    // Collect old() expressions from ensures clauses and save pre-state values
    let mut ensures_exprs: Vec<String> = Vec::new();
    for clause in &f.clauses {
        if clause.kind == ClauseKind::Ensures {
            for (var, rust_expr) in collect_old_exprs(&clause.body) {
                code.push_str(&format!("    let __old_{var} = {rust_expr}.clone();\n"));
            }
            ensures_exprs.push(expr_to_rust(&clause.body));
        }
    }

    // Generate requires assertions at function entry
    for clause in &f.clauses {
        if clause.kind == ClauseKind::Requires {
            let expr = expr_to_rust(&clause.body);
            code.push_str(&format!(
                "    debug_assert!({expr}, \"requires: {}\");\n",
                expr.replace('"', "\\\"")
            ));
        }
    }

    code.push_str(&format!(
        "    let __result: {ret_ty} = todo!(\"implementation provided by AI agent\");\n"
    ));

    // Generate ensures assertions before return
    for ens in &ensures_exprs {
        code.push_str(&format!(
            "    debug_assert!({ens}, \"ensures: {}\");\n",
            ens.replace('"', "\\\"")
        ));
    }

    code.push_str("    __result\n");
    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Service declarations
// ---------------------------------------------------------------------------

fn generate_service(s: &ServiceDecl, code: &mut String) {
    code.push_str(&format!(
        "/// Service: {}\npub mod {} {{\n",
        s.name,
        s.name.to_lowercase()
    ));

    for item in &s.items {
        match item {
            ServiceItem::TypeDef(t) => {
                let mut inner = String::new();
                generate_type_def(t, &mut inner);
                // Indent inner code
                for line in inner.lines() {
                    code.push_str(&format!("    {line}\n"));
                }
            }
            ServiceItem::EnumDef(e) => {
                let mut inner = String::new();
                generate_enum_def(e, &mut inner);
                for line in inner.lines() {
                    code.push_str(&format!("    {line}\n"));
                }
            }
            ServiceItem::States(states) => {
                // Generate a state enum
                code.push_str("    #[derive(Debug, Clone, PartialEq)]\n");
                code.push_str("    pub enum State {\n");
                for state in states {
                    code.push_str(&format!("        {state},\n"));
                }
                code.push_str("    }\n\n");
            }
            ServiceItem::Operation { name, clauses } => {
                code.push_str(&format!("    /// Operation: {name}\n"));
                code.push_str(&format!("    pub fn {name}() {{\n"));
                for clause in clauses {
                    if clause.kind == ClauseKind::Requires {
                        let expr = expr_to_rust(&clause.body);
                        code.push_str(&format!(
                            "        debug_assert!({expr}, \"requires: {}\");\n",
                            expr.replace('"', "\\\"")
                        ));
                    }
                }
                code.push_str("        todo!(\"operation implementation\")\n");
                code.push_str("    }\n\n");
            }
            ServiceItem::Query { name, clauses } => {
                code.push_str(&format!("    /// Query: {name}\n"));
                code.push_str(&format!("    pub fn {name}() {{\n"));
                for clause in clauses {
                    if clause.kind == ClauseKind::Requires {
                        let expr = expr_to_rust(&clause.body);
                        code.push_str(&format!(
                            "        debug_assert!({expr}, \"requires: {}\");\n",
                            expr.replace('"', "\\\"")
                        ));
                    }
                }
                code.push_str("        todo!(\"query implementation\")\n");
                code.push_str("    }\n\n");
            }
            ServiceItem::Invariant(expr) => {
                let rust_expr = expr_to_rust(expr);
                code.push_str(&format!("    // invariant: {rust_expr}\n\n"));
            }
            ServiceItem::Other { kind, body } => {
                let rust_expr = expr_to_rust(body);
                code.push_str(&format!("    // {kind}: {rust_expr}\n\n"));
            }
        }
    }

    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Generic blocks (feature, incremental, etc.)
// ---------------------------------------------------------------------------

fn generate_block(kind: &str, name: &str, body: &[Clause], code: &mut String) {
    code.push_str(&format!(
        "/// {kind}: {name}\npub mod block_{} {{\n",
        name.to_lowercase()
    ));

    for clause in body {
        let expr = expr_to_rust(&clause.body);
        code.push_str(&format!("    // {:?}: {expr}\n", clause.kind));
    }

    code.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Rust formatting via prettyplease
// ---------------------------------------------------------------------------

/// Format a Rust source string via prettyplease.
///
/// If parsing fails (the generated code is not valid Rust syntax),
/// returns the input unchanged with a comment noting the failure.
fn format_rust(code: &str) -> String {
    match syn::parse_file(code) {
        Ok(syntax_tree) => prettyplease::unparse(&syntax_tree),
        Err(e) => {
            eprintln!("warning: generated Rust has syntax errors, skipping formatting: {e}");
            format!("// WARNING: prettyplease formatting skipped (parse error: {e})\n\n{code}")
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: parse + resolve + type-check source text, then codegen.
    fn codegen_ok(source: &str) -> GeneratedProject {
        let (file, errs) = assura_parser::parse(source);
        assert!(errs.is_empty(), "unexpected parse errors: {errs:?}");
        let file = file.expect("parse returned None");
        let resolved = assura_resolve::resolve(&file).expect("resolve failed");
        let typed = assura_types::type_check(&resolved).expect("type check failed");
        codegen(&typed)
    }

    #[test]
    fn empty_file_generates_project() {
        let project = codegen_ok("");
        assert!(!project.cargo_toml.is_empty());
        assert_eq!(project.files.len(), 1);
        assert_eq!(project.files[0].0, "src/lib.rs");
        assert!(
            project.files[0]
                .1
                .contains("Generated by the Assura compiler")
        );
    }

    #[test]
    fn struct_codegen() {
        let project = codegen_ok(
            r#"
type Point {
    x: Int
    y: Int
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("struct Point"), "should contain struct Point");
        assert!(lib.contains("i64"), "should map Int to i64");
    }

    #[test]
    fn enum_codegen() {
        let project = codegen_ok(
            r#"
enum Color {
    Red,
    Green,
    Blue
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("enum Color"), "should contain enum Color");
        assert!(lib.contains("Red"), "should contain Red variant");
        assert!(lib.contains("Green"), "should contain Green variant");
        assert!(lib.contains("Blue"), "should contain Blue variant");
    }

    #[test]
    fn contract_generates_module() {
        let project = codegen_ok(
            r#"
contract SafeDivision {
    requires { true }
    ensures  { true }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("contract_safedivision"),
            "should contain contract module"
        );
    }

    #[test]
    fn fn_def_codegen() {
        // Note: the current parser stores fn clauses in return_ty as raw
        // tokens rather than structured Clause objects. So fn codegen
        // generates the return type string including clause keywords.
        // The codegen still generates a valid function stub.
        let project = codegen_ok(
            r#"
fn helper(n: Int) -> Int {
    requires { n >= 0 }
    ensures  { result >= 0 }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("fn helper"), "should contain fn helper");
    }

    #[test]
    fn contract_generates_debug_assert() {
        let project = codegen_ok(
            r#"
contract Positive {
    requires { true }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("debug_assert!"),
            "contract requires should generate debug_assert"
        );
    }

    #[test]
    fn project_name_used_in_cargo_toml() {
        let project = codegen_ok(
            r#"
project my_cool_project {
    profile: [core]
}

contract Foo {
    requires { true }
}
"#,
        );
        assert!(
            project.cargo_toml.contains("my_cool_project"),
            "Cargo.toml should use the project name"
        );
    }

    #[test]
    fn service_generates_module() {
        let project = codegen_ok(
            r#"
service MyService {
    states: Init -> Running -> Stopped

    operation Start {
        requires: true
    }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("mod myservice"),
            "should contain service module"
        );
        assert!(lib.contains("State"), "should contain state enum");
    }

    #[test]
    fn cargo_toml_well_formed() {
        let project = codegen_ok("");
        assert!(project.cargo_toml.contains("[package]"));
        assert!(project.cargo_toml.contains("edition = \"2024\""));
        assert!(project.cargo_toml.contains("[dependencies]"));
    }

    // -----------------------------------------------------------------------
    // T020: Type mapping tests
    // -----------------------------------------------------------------------

    #[test]
    fn type_mapping_int_to_i64() {
        assert_eq!(map_type_token("Int"), "i64");
    }

    #[test]
    fn type_mapping_nat_to_u64() {
        assert_eq!(map_type_token("Nat"), "u64");
    }

    #[test]
    fn type_mapping_float_to_f64() {
        assert_eq!(map_type_token("Float"), "f64");
    }

    #[test]
    fn type_mapping_bool() {
        assert_eq!(map_type_token("Bool"), "bool");
    }

    #[test]
    fn type_mapping_string() {
        assert_eq!(map_type_token("String"), "String");
    }

    #[test]
    fn type_mapping_bytes_to_vec_u8() {
        assert_eq!(map_type_token("Bytes"), "Vec<u8>");
    }

    #[test]
    fn type_mapping_unit() {
        assert_eq!(map_type_token("Unit"), "()");
    }

    #[test]
    fn type_mapping_never() {
        assert_eq!(map_type_token("Never"), "!");
    }

    #[test]
    fn type_mapping_list_to_vec() {
        assert_eq!(map_type_token("List"), "Vec");
    }

    #[test]
    fn type_mapping_map_to_btreemap() {
        assert_eq!(map_type_token("Map"), "std::collections::BTreeMap");
    }

    #[test]
    fn type_mapping_set_to_btreeset() {
        assert_eq!(map_type_token("Set"), "std::collections::BTreeSet");
    }

    #[test]
    fn type_mapping_option_passthrough() {
        assert_eq!(map_type_token("Option"), "Option");
    }

    #[test]
    fn type_mapping_result_passthrough() {
        assert_eq!(map_type_token("Result"), "Result");
    }

    #[test]
    fn type_mapping_fixed_width() {
        assert_eq!(map_type_token("U8"), "u8");
        assert_eq!(map_type_token("U16"), "u16");
        assert_eq!(map_type_token("U32"), "u32");
        assert_eq!(map_type_token("U64"), "u64");
        assert_eq!(map_type_token("I8"), "i8");
        assert_eq!(map_type_token("I16"), "i16");
        assert_eq!(map_type_token("I32"), "i32");
        assert_eq!(map_type_token("I64"), "i64");
        assert_eq!(map_type_token("F32"), "f32");
        assert_eq!(map_type_token("F64"), "f64");
    }

    #[test]
    fn refined_type_generates_newtype() {
        let project = codegen_ok(
            r#"
type Pos = { n: Int | n > 0 }
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("struct Pos"),
            "refined type should generate a newtype struct"
        );
        assert!(lib.contains("i64"), "refined type base should be i64");
    }

    #[test]
    fn type_alias_codegen() {
        let project = codegen_ok(
            r#"
type UserId = Int
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("UserId"), "should contain type alias name");
    }

    // -----------------------------------------------------------------------
    // T021: Contract codegen tests
    // -----------------------------------------------------------------------

    #[test]
    fn contract_ensures_generates_debug_assert() {
        let project = codegen_ok(
            r#"
contract NonNeg {
    requires { true }
    ensures  { true }
}
"#,
        );
        let lib = &project.files[0].1;
        // Both requires and ensures should produce debug_assert!
        let assert_count = lib.matches("debug_assert!").count();
        assert!(
            assert_count >= 2,
            "should have debug_assert for both requires and ensures, got {assert_count}"
        );
    }

    #[test]
    fn contract_has_result_variable() {
        let project = codegen_ok(
            r#"
contract Foo {
    requires { true }
    ensures  { true }
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("__result"),
            "contract should declare __result variable"
        );
    }

    #[test]
    fn fn_def_ensures_generates_debug_assert() {
        // Note: clauses must be outside the body block for the parser
        // to parse them as structured Clause objects.
        let project = codegen_ok(
            "fn abs(n: Int) -> Int\n    requires { true }\n    ensures  { result >= 0 }\n",
        );
        let lib = &project.files[0].1;
        // requires and ensures should both be debug_assert!
        let assert_count = lib.matches("debug_assert!").count();
        assert!(
            assert_count >= 2,
            "fn should have debug_assert for both requires and ensures, got {assert_count}"
        );
        assert!(
            lib.contains("__result"),
            "fn should declare __result variable"
        );
    }

    #[test]
    fn fn_result_maps_to_dunder_result() {
        let project = codegen_ok("fn double(n: Int) -> Int\n    ensures { result == n + n }\n");
        let lib = &project.files[0].1;
        assert!(
            lib.contains("__result"),
            "result keyword in ensures should map to __result"
        );
    }

    // -----------------------------------------------------------------------
    // T022: Cargo project generation tests
    // -----------------------------------------------------------------------

    #[test]
    fn cargo_toml_has_package_name() {
        let project = codegen_ok(
            r#"
project test_project {
    profile: [core]
}
"#,
        );
        assert!(project.cargo_toml.contains("test_project"));
        assert!(project.cargo_toml.contains("[package]"));
    }

    #[test]
    fn default_project_name_is_generated() {
        let project = codegen_ok("");
        assert!(
            project.cargo_toml.contains("\"generated\""),
            "default project name should be 'generated'"
        );
    }

    #[test]
    fn generated_file_is_src_lib_rs() {
        let project = codegen_ok(
            r#"
type X {
    val: Int
}
"#,
        );
        assert_eq!(project.files.len(), 1);
        assert_eq!(project.files[0].0, "src/lib.rs");
    }

    #[test]
    fn generated_rust_has_header_comment() {
        let project = codegen_ok("");
        let lib = &project.files[0].1;
        assert!(lib.contains("Generated by the Assura compiler"));
        assert!(lib.contains("Do not edit manually"));
    }

    // -----------------------------------------------------------------------
    // T023: Struct and enum codegen tests
    // -----------------------------------------------------------------------

    #[test]
    fn struct_has_derive_debug_clone_partialeq() {
        let project = codegen_ok(
            r#"
type Pair {
    a: Int
    b: Int
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("Debug"), "struct should derive Debug");
        assert!(lib.contains("Clone"), "struct should derive Clone");
        assert!(lib.contains("PartialEq"), "struct should derive PartialEq");
    }

    #[test]
    fn struct_field_types_are_mapped() {
        let project = codegen_ok(
            r#"
type Config {
    name: String
    count: Nat
    enabled: Bool
    ratio: Float
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("String"), "String should map to String");
        assert!(lib.contains("u64"), "Nat should map to u64");
        assert!(lib.contains("bool"), "Bool should map to bool");
        assert!(lib.contains("f64"), "Float should map to f64");
    }

    #[test]
    fn struct_pub_field_visibility() {
        let project = codegen_ok(
            r#"
type Visible {
    pub x: Int
    y: Int
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(
            lib.contains("pub x"),
            "pub field should have pub visibility in generated code"
        );
    }

    #[test]
    fn enum_has_derive_debug_clone_partialeq() {
        let project = codegen_ok(
            r#"
enum Direction {
    North,
    South,
    East,
    West
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("Debug"), "enum should derive Debug");
        assert!(lib.contains("Clone"), "enum should derive Clone");
        assert!(lib.contains("PartialEq"), "enum should derive PartialEq");
    }

    #[test]
    fn enum_variant_with_data() {
        let project = codegen_ok(
            r#"
enum Value {
    Num(Int),
    Text(String),
    Nothing
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("Num"), "should contain Num variant");
        assert!(lib.contains("i64"), "Int should map to i64 in variant");
        assert!(lib.contains("Text"), "should contain Text variant");
        assert!(
            lib.contains("Nothing"),
            "should contain unit variant Nothing"
        );
    }

    #[test]
    fn empty_struct_codegen() {
        let project = codegen_ok(
            r#"
type Marker {
}
"#,
        );
        let lib = &project.files[0].1;
        assert!(lib.contains("Marker"), "should contain empty struct");
    }

    // -----------------------------------------------------------------------
    // T028: End-to-end SafeDivision contract test
    // -----------------------------------------------------------------------

    #[test]
    fn e2e_safe_division_check_passes() {
        // Parse the e2e test file through the full pipeline
        let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
            .expect("failed to read safe_division.assura");
        let (file, errs) = assura_parser::parse(&source);
        assert!(
            errs.is_empty(),
            "SafeDivision should parse without errors: {errs:?}"
        );
        let file = file.expect("parse returned None");
        let resolved = assura_resolve::resolve(&file).expect("resolution should succeed");
        let typed = assura_types::type_check(&resolved).expect("type check should succeed");

        // Codegen should succeed
        let project = codegen(&typed);
        assert!(
            !project.cargo_toml.is_empty(),
            "Cargo.toml should not be empty"
        );
        assert_eq!(
            project.files.len(),
            1,
            "should produce exactly one source file"
        );
        assert_eq!(project.files[0].0, "src/lib.rs");
    }

    #[test]
    fn e2e_safe_division_generates_debug_assert_for_requires() {
        let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
            .expect("failed to read safe_division.assura");
        let project = codegen_ok(&source);
        let lib = &project.files[0].1;

        // The requires clause `b != 0` must produce a debug_assert
        assert!(
            lib.contains("debug_assert!"),
            "generated code must contain debug_assert!"
        );
        assert!(
            lib.contains("b != 0"),
            "generated code must contain the requires predicate 'b != 0'"
        );
    }

    #[test]
    fn e2e_safe_division_generates_ensures_assertion() {
        let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
            .expect("failed to read safe_division.assura");
        let project = codegen_ok(&source);
        let lib = &project.files[0].1;

        // The ensures clause should produce a debug_assert with the postcondition
        assert!(
            lib.contains("a % b"),
            "generated code must contain modulo expression from ensures"
        );
        // At least two debug_assert! calls: one for requires, one for ensures
        let assert_count = lib.matches("debug_assert!").count();
        assert!(
            assert_count >= 2,
            "should have debug_assert for both requires and ensures, got {assert_count}"
        );
    }

    #[test]
    fn e2e_safe_division_has_correct_signature() {
        let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
            .expect("failed to read safe_division.assura");
        let project = codegen_ok(&source);
        let lib = &project.files[0].1;

        // Should have input params mapped to i64
        assert!(lib.contains("a: i64"), "input param 'a' should map to i64");
        assert!(lib.contains("b: i64"), "input param 'b' should map to i64");
        // Should have the contract module
        assert!(
            lib.contains("contract_safedivision"),
            "should contain the SafeDivision contract module"
        );
    }

    #[test]
    fn e2e_safe_division_generated_rust_is_valid() {
        let source = std::fs::read_to_string("../../tests/e2e/safe_division.assura")
            .expect("failed to read safe_division.assura");
        let project = codegen_ok(&source);
        let lib = &project.files[0].1;

        // Verify the generated Rust parses as valid syntax via syn
        syn::parse_file(lib).expect("generated Rust should be valid syntax");
    }

    // -----------------------------------------------------------------------
    // T043 CORE.1: Ghost code erasure tests
    // -----------------------------------------------------------------------

    #[test]
    fn ghost_fn_produces_no_output() {
        // A ghost function should be completely erased in generated code.
        let project =
            codegen_ok("ghost fn spec_helper(x: Int) -> Bool\n    ensures { result == true }\n");
        let lib = &project.files[0].1;
        assert!(
            !lib.contains("fn spec_helper"),
            "ghost fn should not appear in generated Rust code"
        );
    }

    #[test]
    fn non_ghost_fn_still_generated() {
        // A normal (non-ghost) function should still be generated.
        let project = codegen_ok("fn normal_helper(x: Int) -> Int\n    ensures { result >= 0 }\n");
        let lib = &project.files[0].1;
        assert!(
            lib.contains("fn normal_helper"),
            "non-ghost fn should appear in generated Rust code"
        );
    }

    #[test]
    fn ghost_block_erased_in_expr() {
        // A ghost block expression should produce erased output.
        let expr = Expr::Ghost(Box::new(Expr::Literal(Literal::Bool(true))));
        let rust = expr_to_rust(&expr);
        assert!(
            rust.contains("ghost erased"),
            "ghost block should generate erased marker, got: {rust}"
        );
    }

    // -----------------------------------------------------------------------
    // T044 CORE.2: Lemma erasure tests
    // -----------------------------------------------------------------------

    #[test]
    fn lemma_fn_produces_no_output() {
        // A lemma function should be completely erased in generated code.
        let project =
            codegen_ok("lemma add_comm(a: Int, b: Int)\n    ensures { a + b == b + a }\n");
        let lib = &project.files[0].1;
        assert!(
            !lib.contains("fn add_comm"),
            "lemma fn should not appear in generated Rust code"
        );
    }

    #[test]
    fn apply_expr_erased_in_codegen() {
        // apply lemma_name(args) should produce a comment, not code.
        let expr = Expr::Apply {
            lemma_name: "my_lemma".into(),
            args: vec![Expr::Literal(Literal::Int("42".into()))],
        };
        let rust = expr_to_rust(&expr);
        assert!(
            rust.contains("lemma my_lemma applied"),
            "apply should generate erased comment, got: {rust}"
        );
    }

    #[test]
    fn match_expr_codegen() {
        // match expression should generate Rust match syntax
        let expr = Expr::Match {
            scrutinee: Box::new(Expr::Ident("status".into())),
            arms: vec![
                assura_parser::ast::MatchArm {
                    pattern: assura_parser::ast::Pattern::Ident("Active".into()),
                    body: Expr::Literal(Literal::Int("1".into())),
                },
                assura_parser::ast::MatchArm {
                    pattern: assura_parser::ast::Pattern::Wildcard,
                    body: Expr::Literal(Literal::Int("0".into())),
                },
            ],
        };
        let rust = expr_to_rust(&expr);
        assert!(
            rust.contains("match status"),
            "should have match keyword: {rust}"
        );
        assert!(
            rust.contains("Active => 1"),
            "should have Active arm: {rust}"
        );
        assert!(rust.contains("_ => 0"), "should have wildcard arm: {rust}");
    }

    #[test]
    fn non_lemma_fn_still_generated() {
        // A normal (non-lemma) function should still be generated.
        let project = codegen_ok("fn helper(n: Int) -> Int\n    ensures { result >= 0 }\n");
        let lib = &project.files[0].1;
        assert!(
            lib.contains("fn helper"),
            "non-lemma fn should appear in generated Rust code"
        );
    }

    // =======================================================================
    // T119: Cranelift backend configuration
    // =======================================================================

    #[test]
    fn backend_default_is_rustc() {
        let config = super::BackendConfig::default();
        assert_eq!(config.backend, super::CodegenBackend::Rustc);
    }

    #[test]
    fn backend_cranelift_fast_dev() {
        let config = super::BackendConfig {
            backend: super::CodegenBackend::Cranelift,
            opt_level: 0,
            debug_info: true,
        };
        assert_eq!(config.backend, super::CodegenBackend::Cranelift);
        assert_eq!(config.opt_level, 0);
    }
}
