//! Type mapping, Cargo.toml generation, and type definition codegen.

use super::*;

pub(crate) fn generate_cargo_toml_impl(
    crate_name: &str,
    config: &BackendConfig,
    include_proptest: bool,
    include_thiserror: bool,
) -> String {
    let mut toml = format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

# Generated by the Assura compiler.
# Do not edit manually.

[dependencies]
"#
    );

    if include_thiserror {
        toml.push_str("thiserror = \"2\"\n");
    }

    if include_proptest {
        toml.push_str("\n[dev-dependencies]\nproptest = \"1\"\n");
    }

    // Add profile configuration based on BackendConfig
    if config.opt_level != 2 || config.debug_info {
        toml.push_str("\n[profile.release]\n");
        toml.push_str(&format!("opt-level = {}\n", config.opt_level));
        if config.debug_info {
            toml.push_str("debug = true\n");
        }
    }

    // Add backend-specific configuration
    if matches!(config.backend, CodegenBackend::Cranelift) {
        toml.push_str(
            "\n# Cranelift backend for fast dev builds\n\
             # Install: rustup component add rustc-codegen-cranelift\n\
             # Note: Cranelift requires nightly Rust\n",
        );
        // Force dev-friendly profile settings for Cranelift
        if config.opt_level == 2 && !config.debug_info {
            toml.push_str("\n[profile.dev]\nopt-level = 0\ndebug = true\n");
        }
    }

    // WASM target: add cdylib crate type so cargo produces a .wasm file
    if matches!(config.target, CompileTarget::Wasm) {
        toml.push_str("\n[lib]\ncrate-type = [\"cdylib\"]\n");
        toml.push_str(
            "\n# WASM target: build with `cargo build --target wasm32-wasip1`\n\
             # Install target: `rustup target add wasm32-wasip1`\n",
        );
    }

    toml
}

// ---------------------------------------------------------------------------
// Type mapping: Assura types -> Rust types
// ---------------------------------------------------------------------------

/// Map a single Assura type token to its Rust equivalent.
pub(crate) fn map_type_token(tok: &str) -> &str {
    match tok {
        "Int" => "i64",
        "Nat" => "u64",
        "Float" => "f64",
        "Bool" => "bool",
        "String" => "String",
        "Bytes" => "Vec<u8>",
        "Unit" => "()",
        "Never" => "!",
        "U8" => "u8",
        "U16" => "u16",
        "U32" => "u32",
        "U64" => "u64",
        "I8" => "i8",
        "I16" => "i16",
        "I32" => "i32",
        "I64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "List" => "Vec",
        "Map" => "std::collections::BTreeMap",
        "Set" => "std::collections::BTreeSet",
        "Sequence" => "Vec",
        // Option, Result map to themselves
        _ => tok,
    }
}

/// Convert an Assura type token sequence (e.g., `["List", "<", "Int", ">"]`)
/// to a valid Rust type string.
///
/// Handles Assura-specific syntax that is not valid Rust:
/// - Refinement types: `{ x : T | P }` -> base type `T`
/// - Taint annotations: `T @ taint : label` -> just `T`
/// - Union error types: `T | E` -> `Result<T, E>`
/// - Smart joining: `Vec < i64 >` -> `Vec<i64>`
pub(crate) fn map_type_tokens(tokens: &[String]) -> String {
    if tokens.is_empty() {
        return "()".to_string();
    }

    // Phase 1: Strip annotations and clause keywords that leak into type tokens
    // Stops at: "@" (taint), "#" (attribute), "decreases", "where"
    let clean: Vec<&str> = tokens
        .iter()
        .map(|s| s.as_str())
        .take_while(|t| !matches!(*t, "@" | "#" | "decreases" | "where"))
        .collect();
    if clean.is_empty() {
        return "()".to_string();
    }

    // Phase 2: Strip refinement predicates: { x : T | P } -> just the base type
    if clean.first() == Some(&"{") {
        return extract_base_type_from_refined(tokens);
    }

    // Phase 3: Handle union error types: T | E -> Result<T, E>
    // Find a "|" not inside angle brackets
    let mut depth = 0i32;
    let mut pipe_pos = None;
    for (i, tok) in clean.iter().enumerate() {
        match *tok {
            "<" => depth += 1,
            ">" => {
                if depth > 0 {
                    depth -= 1;
                }
            }
            "|" if depth == 0 => {
                pipe_pos = Some(i);
                break;
            }
            _ => {}
        }
    }

    if let Some(pos) = pipe_pos {
        let ok_tokens: Vec<String> = clean[..pos].iter().map(|s| s.to_string()).collect();
        let err_tokens: Vec<String> = clean[pos + 1..].iter().map(|s| s.to_string()).collect();
        let ok_type = map_type_tokens(&ok_tokens);
        let err_type = map_type_tokens(&err_tokens);
        return format!("Result<{ok_type}, {err_type}>");
    }

    // Phase 4: Map each token and join smartly (no extra spaces around < > & etc.)
    // Convert SCREAMING_SNAKE_CASE names inside angle brackets to marker types,
    // since Assura const-generics don't translate directly to Rust generics.
    let mut in_angle = 0i32;
    let mapped: Vec<String> = clean
        .iter()
        .map(|t| {
            match *t {
                "<" => in_angle += 1,
                ">" if in_angle > 0 => {
                    in_angle -= 1;
                }
                _ => {}
            }
            if in_angle > 0 && is_const_name(t) {
                // Const-generic name used as type param: wrap as marker type
                t.to_string()
            } else {
                map_type_token(t).to_string()
            }
        })
        .collect();
    let refs: Vec<&str> = mapped.iter().map(|s| s.as_str()).collect();
    smart_join_type_tokens(&refs)
}

/// Join type tokens without spurious spaces around angle brackets, ampersands, etc.
pub(crate) fn smart_join_type_tokens(tokens: &[&str]) -> String {
    let mut result = String::new();
    for (i, tok) in tokens.iter().enumerate() {
        if i > 0 {
            let prev = tokens[i - 1];
            let no_space = matches!(*tok, ">" | "," | ")" | ".")
                || matches!(prev, "<" | "(" | "&" | ".")
                || (*tok == "mut" && prev == "&");
            if !no_space {
                result.push(' ');
            }
        }
        result.push_str(tok);
    }
    result
}

// ---------------------------------------------------------------------------

// Type definitions
// ---------------------------------------------------------------------------

pub(crate) fn generate_type_def(t: &TypeDef, code: &mut String) {
    let tps = if t.type_params.is_empty() {
        String::new()
    } else {
        format!("<{}>", t.type_params.join(", "))
    };

    match &t.body {
        TypeBody::Struct(fields) => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps} {{\n",
                t.name
            ));
            for f in fields {
                let vis = if f.is_pub { "pub " } else { "" };
                let ty = map_type_tokens(&f.ty);
                code.push_str(&format!("    {vis}{}: {ty},\n", f.name));
            }
            code.push_str("}\n\n");
        }
        TypeBody::Alias(tokens) => {
            let ty = map_type_tokens(tokens);
            code.push_str(&format!("pub type {}{tps} = {ty};\n\n", t.name));
        }
        TypeBody::Refined(tokens) => {
            let base_ty = extract_base_type_from_refined(tokens);
            code.push_str(&format!(
                "/// Refined type: {}\n#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps}(pub {base_ty});\n\n",
                tokens.join(" "),
                t.name
            ));
        }
        TypeBody::Empty => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq)]\npub struct {}{tps};\n\n",
                t.name
            ));
        }
    }
}

// ---------------------------------------------------------------------------
// Type reference collection (for generating stub types)
// ---------------------------------------------------------------------------

/// Check if a name looks like a constant (SCREAMING_SNAKE_CASE).
/// E.g., `TOTAL_TABLE_SIZE`, `MAX_ALPHABET_SIZE`.
pub(crate) fn is_const_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit())
        && name.contains('_')
}

/// Info about a generic parameter: either a type param or a const param.
#[derive(Debug, Clone)]
pub(crate) enum GenericParamKind {
    Type,
    Const,
}

/// Scan a type token sequence for `TypeName<Arg1, Arg2, ...>` patterns.
/// Records the generic params (type vs const) for each type name, and
/// collects names that appear as const-generic arguments.
pub(crate) fn detect_generic_arity(
    tokens: &[String],
    param_map: &mut std::collections::HashMap<String, Vec<GenericParamKind>>,
    const_names: &mut std::collections::HashSet<String>,
) {
    let mut i = 0;
    while i < tokens.len() {
        if i + 1 < tokens.len() && tokens[i + 1] == "<" && is_user_type_name(&tokens[i]) {
            let type_name = tokens[i].clone();
            let mut depth = 0;
            let mut params = Vec::new();
            let mut current_is_const = false;
            let mut j = i + 1;
            while j < tokens.len() {
                match tokens[j].as_str() {
                    "<" => {
                        depth += 1;
                        if depth == 1 {
                            current_is_const = false;
                        }
                    }
                    ">" if depth > 0 => {
                        depth -= 1;
                        if depth == 0 {
                            // Record the last parameter
                            params.push(if current_is_const {
                                GenericParamKind::Const
                            } else {
                                GenericParamKind::Type
                            });
                            break;
                        }
                    }
                    "," if depth == 1 => {
                        params.push(if current_is_const {
                            GenericParamKind::Const
                        } else {
                            GenericParamKind::Type
                        });
                        current_is_const = false;
                    }
                    tok if depth == 1 && is_const_name(tok) => {
                        const_names.insert(tok.to_string());
                        current_is_const = true;
                    }
                    tok if depth == 1
                        && !tok.is_empty()
                        && tok.chars().all(|c| c.is_ascii_digit()) =>
                    {
                        // Numeric literal as const generic
                        current_is_const = true;
                    }
                    _ => {}
                }
                j += 1;
            }
            let existing_len = param_map.get(&type_name).map_or(0, |v| v.len());
            if params.len() > existing_len {
                param_map.insert(type_name, params);
            }
            i = j + 1;
        } else {
            i += 1;
        }
    }
}

/// Check if a token looks like a user-defined type name (starts with uppercase,
/// alphanumeric, not a Rust keyword or built-in).
pub(crate) fn is_user_type_name(tok: &str) -> bool {
    !tok.is_empty()
        && tok.chars().next().is_some_and(|c| c.is_uppercase())
        && tok.chars().all(|c| c.is_alphanumeric() || c == '_')
        && !matches!(
            tok,
            "Int"
                | "Nat"
                | "Float"
                | "Bool"
                | "String"
                | "Bytes"
                | "Unit"
                | "Never"
                | "U8"
                | "U16"
                | "U32"
                | "U64"
                | "I8"
                | "I16"
                | "I32"
                | "I64"
                | "F32"
                | "F64"
                | "List"
                | "Vec"
                | "Map"
                | "Set"
                | "Option"
                | "Result"
                | "Sequence"
                | "Self"
                | "Box"
                | "Fn"
                | "FnOnce"
                | "FnMut"
        )
}

/// Collect user-defined type names from a type token sequence.
pub(crate) fn collect_type_refs_from_tokens(
    tokens: &[String],
    out: &mut std::collections::HashSet<String>,
) {
    for tok in tokens {
        // Skip taint annotations, attributes, and keywords
        if matches!(
            tok.as_str(),
            "@" | "#"
                | "taint"
                | "untrusted"
                | "validated"
                | "secret"
                | "pub"
                | "mut"
                | ":"
                | "|"
                | "&"
                | ">"
                | "<"
                | ","
                | "("
                | ")"
                | "{"
                | "}"
                | "["
                | "]"
                | "decreases"
                | "where"
        ) {
            continue;
        }
        if is_user_type_name(tok) {
            out.insert(tok.clone());
        }
    }
}

/// Collect type names referenced in expressions (e.g., constructor calls).
pub(crate) fn collect_type_refs_from_expr(
    expr: &Expr,
    out: &mut std::collections::HashSet<String>,
) {
    match expr {
        Expr::Ident(name) => {
            if is_user_type_name(name) {
                out.insert(name.clone());
            }
        }
        Expr::Call { func, args } => {
            collect_type_refs_from_expr(func, out);
            for a in args {
                collect_type_refs_from_expr(a, out);
            }
        }
        Expr::MethodCall {
            receiver,
            method: _,
            args,
        } => {
            collect_type_refs_from_expr(receiver, out);
            for a in args {
                collect_type_refs_from_expr(a, out);
            }
        }
        Expr::Field(recv, _) => collect_type_refs_from_expr(recv, out),
        Expr::Index { expr: e, index } => {
            collect_type_refs_from_expr(e, out);
            collect_type_refs_from_expr(index, out);
        }
        Expr::BinOp { lhs, rhs, .. } => {
            collect_type_refs_from_expr(lhs, out);
            collect_type_refs_from_expr(rhs, out);
        }
        Expr::UnaryOp { expr: e, .. }
        | Expr::Old(e)
        | Expr::Paren(e)
        | Expr::Cast { expr: e, .. }
        | Expr::Ghost(e) => {
            collect_type_refs_from_expr(e, out);
        }
        Expr::If {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_type_refs_from_expr(cond, out);
            collect_type_refs_from_expr(then_branch, out);
            if let Some(eb) = else_branch {
                collect_type_refs_from_expr(eb, out);
            }
        }
        Expr::Forall { domain, body, .. } | Expr::Exists { domain, body, .. } => {
            collect_type_refs_from_expr(domain, out);
            collect_type_refs_from_expr(body, out);
        }
        Expr::Let { value, body, .. } => {
            collect_type_refs_from_expr(value, out);
            collect_type_refs_from_expr(body, out);
        }
        Expr::Match { scrutinee, arms } => {
            collect_type_refs_from_expr(scrutinee, out);
            for arm in arms {
                collect_type_refs_from_expr(&arm.body, out);
            }
        }
        Expr::Apply { args, .. } => {
            for a in args {
                collect_type_refs_from_expr(a, out);
            }
        }
        Expr::List(items) | Expr::Tuple(items) | Expr::Block(items) => {
            for item in items {
                collect_type_refs_from_expr(item, out);
            }
        }
        Expr::Raw(tokens) => {
            for tok in tokens {
                if is_user_type_name(tok) {
                    out.insert(tok.clone());
                }
            }
        }
        // Literals never contain type references
        Expr::Literal(_) => {}
    }
}

/// Find the value for a feature_max constant from the AST.
pub(crate) fn find_feature_max_value(
    source: &assura_parser::ast::SourceFile,
    name: &str,
) -> String {
    for decl in &source.decls {
        if let Decl::Block {
            kind,
            name: n,
            value,
            body,
        } = &decl.node
            && *kind == BlockKind::FeatureMax
            && n == name
        {
            // First, try the inline value field.
            // The value tokens may include a type annotation: `["Nat", "=", "280"]`
            // from `feature_max X: Nat = 280`. Extract after the `=`.
            if let Some(val_tokens) = value {
                if let Some(eq_pos) = val_tokens.iter().position(|t| t == "=") {
                    let after_eq = &val_tokens[eq_pos + 1..];
                    if !after_eq.is_empty() {
                        return after_eq.join(" ");
                    }
                } else if val_tokens.len() == 1 {
                    // Single-token value without `=` (e.g., just a number)
                    return val_tokens[0].clone();
                }
            }
            // Fallback: try to extract from body clauses
            for clause in body {
                let val = expr_to_rust_static(&clause.body);
                if !val.is_empty() && val != "()" {
                    return val;
                }
            }
        }
    }
    // No value found: emit a compile_error! so generated code fails to
    // build rather than silently using 0, which hides missing definitions.
    format!("compile_error!(\"feature_max `{name}` has no value\")")
}

/// Convert an Expr to a Rust expression for use in const context.
pub fn expr_to_rust_static(expr: &Expr) -> String {
    match expr {
        Expr::Literal(lit) => match lit {
            Literal::Int(s) | Literal::Float(s) => s.clone(),
            Literal::Str(s) => format!("\"{s}\""),
            Literal::Bool(b) => b.to_string(),
        },
        Expr::Ident(s) => s.clone(),
        Expr::BinOp { lhs, op, rhs } => {
            let op_s = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::And => "&&",
                BinOp::Or => "||",
                BinOp::Eq => "==",
                BinOp::Neq => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Lte => "<=",
                BinOp::Gte => ">=",
                BinOp::Implies => "/* implies */",
                BinOp::In => "/* in */",
                BinOp::NotIn => "/* not in */",
                BinOp::Concat => "/* ++ */",
                BinOp::Range => "..",
            };
            format!(
                "({} {op_s} {})",
                expr_to_rust_static(lhs),
                expr_to_rust_static(rhs)
            )
        }
        Expr::Paren(inner) => expr_to_rust_static(inner),
        Expr::UnaryOp {
            op: UnaryOp::Neg,
            expr: e,
        } => {
            let inner = expr_to_rust_static(e);
            format!("-{inner}")
        }
        Expr::UnaryOp {
            op: UnaryOp::Not,
            expr: e,
        } => {
            let inner = expr_to_rust_static(e);
            format!("!{inner}")
        }
        Expr::Field(receiver, field) => {
            let recv = expr_to_rust_static(receiver);
            format!("{recv}.{field}")
        }
        Expr::Call { func, args } => {
            let f = expr_to_rust_static(func);
            let a: Vec<String> = args.iter().map(expr_to_rust_static).collect();
            format!("{f}({})", a.join(", "))
        }
        Expr::MethodCall {
            receiver,
            method,
            args,
        } => {
            let recv = expr_to_rust_static(receiver);
            let a: Vec<String> = args.iter().map(expr_to_rust_static).collect();
            format!("{recv}.{method}({})", a.join(", "))
        }
        Expr::If {
            cond,
            then_branch,
            else_branch,
        } => {
            let c = expr_to_rust_static(cond);
            let t = expr_to_rust_static(then_branch);
            if let Some(e) = else_branch {
                let e = expr_to_rust_static(e);
                format!("if {c} {{ {t} }} else {{ {e} }}")
            } else {
                format!("if {c} {{ {t} }}")
            }
        }
        Expr::Index { expr: e, index } => {
            let base = expr_to_rust_static(e);
            let idx = expr_to_rust_static(index);
            format!("{base}[{idx}]")
        }
        Expr::Old(inner) => {
            // old() is a verification concept; in generated Rust, just emit the inner expr
            expr_to_rust_static(inner)
        }
        Expr::Ghost(inner) => {
            // Ghost expressions are erased at runtime; emit as comment
            let inner_s = expr_to_rust_static(inner);
            format!("/* ghost: {inner_s} */ ()")
        }
        Expr::Cast { expr: e, ty } => {
            let inner = expr_to_rust_static(e);
            format!("({inner} as {ty})")
        }
        Expr::List(items) => {
            let elems: Vec<String> = items.iter().map(expr_to_rust_static).collect();
            format!("vec![{}]", elems.join(", "))
        }
        Expr::Tuple(items) => {
            let elems: Vec<String> = items.iter().map(expr_to_rust_static).collect();
            format!("({})", elems.join(", "))
        }
        Expr::Let { name, value, body } => {
            let v = expr_to_rust_static(value);
            let b = expr_to_rust_static(body);
            format!("{{ let {name} = {v}; {b} }}")
        }
        Expr::Match { scrutinee, arms } => {
            let scrut = expr_to_rust_static(scrutinee);
            let arm_strs: Vec<String> = arms
                .iter()
                .map(|arm| {
                    let pat = match &arm.pattern {
                        assura_parser::ast::Pattern::Ident(s) => s.clone(),
                        assura_parser::ast::Pattern::Wildcard => "_".to_string(),
                        assura_parser::ast::Pattern::Literal(lit) => match lit {
                            Literal::Int(s) | Literal::Float(s) => s.clone(),
                            Literal::Str(s) => format!("\"{s}\""),
                            Literal::Bool(b) => b.to_string(),
                        },
                        assura_parser::ast::Pattern::Constructor { name, fields } => {
                            if fields.is_empty() {
                                name.clone()
                            } else {
                                format!("{name}(..)")
                            }
                        }
                        assura_parser::ast::Pattern::Tuple(pats) => {
                            let ps: Vec<&str> = pats.iter().map(|_| "_").collect();
                            format!("({})", ps.join(", "))
                        }
                    };
                    let body = expr_to_rust_static(&arm.body);
                    format!("{pat} => {body}")
                })
                .collect();
            format!("match {scrut} {{ {} }}", arm_strs.join(", "))
        }
        Expr::Block(exprs) => {
            let strs: Vec<String> = exprs.iter().map(expr_to_rust_static).collect();
            strs.join(" ")
        }
        Expr::Forall { var, domain, body } => {
            // Verification-only; emit as a comment in generated Rust
            let d = expr_to_rust_static(domain);
            let b = expr_to_rust_static(body);
            format!("/* forall {var} in {d}: {b} */ true")
        }
        Expr::Exists { var, domain, body } => {
            let d = expr_to_rust_static(domain);
            let b = expr_to_rust_static(body);
            format!("/* exists {var} in {d}: {b} */ true")
        }
        Expr::Apply { lemma_name, args } => {
            // Verification-only; emit as comment
            let a: Vec<String> = args.iter().map(expr_to_rust_static).collect();
            format!("/* apply {lemma_name}({}) */ ()", a.join(", "))
        }
        Expr::Raw(tokens) => {
            // Try to extract a simple numeric literal from raw tokens
            let clean: Vec<&str> = tokens.iter().map(|s| s.as_str()).collect();
            if clean.len() == 1 {
                return clean[0].to_string();
            }
            // For "= value" patterns (common in feature_max)
            if clean.len() >= 2 && clean[0] == "=" {
                return clean[1..].join(" ");
            }
            clean.join(" ")
        }
    }
}

/// Extract the base type from a refined type token sequence like
/// `["n", ":", "Int", "|", "n", ">", "0"]` -> "i64".
pub(crate) fn extract_base_type_from_refined(tokens: &[String]) -> String {
    // Look for a token after ':' that starts with uppercase
    let mut after_colon = false;
    for tok in tokens {
        if tok == ":" {
            after_colon = true;
            continue;
        }
        if after_colon {
            if tok.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
                return map_type_token(tok).to_string();
            }
            // Not a type, stop looking
            after_colon = false;
        }
    }
    // Fallback: just use the first type-looking token
    for tok in tokens {
        if tok.chars().next().is_some_and(|c| c.is_ascii_uppercase()) {
            return map_type_token(tok).to_string();
        }
    }
    "i64".to_string()
}
