//! SMT-LIB2 dump and quantifier bound validation.
//!
//! Contains `dump_smt_queries()` for `--dump-smt` support and
//! `validate_quantifier_bounds()` for detecting infinite-domain quantifiers.

use assura_parser::ast::{ClauseKind, Decl, Expr, ServiceItem};
use assura_types::TypedFile;

// ---------------------------------------------------------------------------
// Quantifier bound validation
// ---------------------------------------------------------------------------

/// A warning about a quantifier with an infinite (or potentially infinite) domain.
#[derive(Debug, Clone, PartialEq)]
pub struct UnboundedQuantifierWarning {
    /// Name of the enclosing contract/function.
    pub context: String,
    /// The quantifier variable name.
    pub var: String,
    /// Description of the domain.
    pub domain_desc: String,
    /// Why this is problematic.
    pub reason: String,
}

/// Known type names that represent infinite or unbounded domains.
/// Quantifying over these with forall/exists is almost certainly a mistake
/// or will cause SMT solver timeouts.
const INFINITE_TYPE_NAMES: &[&str] = &[
    "Int", "Nat", "Float", "Bool", "String", "Bytes", "U8", "U16", "U32", "U64", "I8", "I16",
    "I32", "I64", "F32", "F64",
];

// ---------------------------------------------------------------------------
// SMT-LIB2 dump (--dump-smt)
// ---------------------------------------------------------------------------

/// A single SMT query with its SMT-LIB2 text and metadata.
pub struct SmtQuery {
    /// Contract or function name containing the clause.
    pub context: String,
    /// Clause kind (e.g., "ensures", "invariant").
    pub kind: String,
    /// The SMT-LIB2 script text.
    pub script: String,
}

/// Generate SMT-LIB2 query scripts for all verifiable clauses in a typed file.
///
/// Returns one `SmtQuery` per clause without invoking any solver. Used by
/// `--dump-smt` to write .smt2 files for offline analysis.
pub fn dump_smt_queries(typed: &TypedFile) -> Vec<SmtQuery> {
    let mut queries = Vec::new();
    for decl in &typed.resolved.source.decls {
        let (name, clauses) = match &decl.node {
            Decl::Contract(c) => (c.name.clone(), &c.clauses[..]),
            Decl::FnDef(f) => (f.name.clone(), &f.clauses[..]),
            Decl::Extern(e) => (e.name.clone(), &e.clauses[..]),
            _ => continue,
        };

        let requires_exprs: Vec<&Expr> = clauses
            .iter()
            .filter(|c| c.kind == ClauseKind::Requires)
            .map(|c| &c.body)
            .collect();

        for clause in clauses {
            let kind_str = match &clause.kind {
                ClauseKind::Ensures => "ensures",
                ClauseKind::Invariant => "invariant",
                ClauseKind::Decreases => "decreases",
                ClauseKind::Rule => "rule",
                ClauseKind::MustNot => "must_not",
                _ => continue,
            };

            let mut vars = std::collections::HashSet::new();
            for req in &requires_exprs {
                crate::cvc5_collect::collect_vars(req, &mut vars);
            }
            crate::cvc5_collect::collect_vars(&clause.body, &mut vars);

            let mut script = String::new();
            script.push_str("; Generated by assura --dump-smt\n");
            script.push_str(&format!("; Context: {name}::{kind_str}\n"));
            script.push_str("(set-logic ALL)\n\n");

            for var in &vars {
                script.push_str(&format!("(declare-const {var} Int)\n"));
            }
            script.push('\n');

            for req in &requires_exprs {
                if let Some(smt) = crate::cvc5_expr_smtlib::expr_to_smtlib(req) {
                    script.push_str(&format!("; requires\n(assert {smt})\n"));
                }
            }

            if let Some(smt) = crate::cvc5_expr_smtlib::expr_to_smtlib(&clause.body) {
                if matches!(clause.kind, ClauseKind::Invariant) {
                    script.push_str(&format!(
                        "; invariant (check satisfiability)\n(assert {smt})\n"
                    ));
                } else {
                    script.push_str(&format!(
                        "; {kind_str} (check validity via negation)\n(assert (not {smt}))\n"
                    ));
                }
            } else {
                script.push_str("; ERROR: could not encode clause to SMT-LIB2\n");
            }

            script.push_str("\n(check-sat)\n(get-model)\n");

            queries.push(SmtQuery {
                context: name.clone(),
                kind: kind_str.to_string(),
                script,
            });
        }
    }
    queries
}

/// Check all quantifiers (forall/exists) in a typed file for unbounded domains.
///
/// Returns warnings for quantifiers that range over infinite type domains
/// (e.g., `forall x in Int: ...`). These are technically valid in the spec
/// but are almost always unintended and cause SMT solver timeouts or
/// unsound verification (if the solver times out and the result is treated
/// as "verified").
pub fn validate_quantifier_bounds(typed: &TypedFile) -> Vec<UnboundedQuantifierWarning> {
    let mut warnings = Vec::new();
    for decl in &typed.resolved.source.decls {
        match &decl.node {
            Decl::Contract(c) => {
                for clause in &c.clauses {
                    collect_unbounded_quantifiers(&clause.body, &c.name, &mut warnings);
                }
            }
            Decl::FnDef(f) => {
                for clause in &f.clauses {
                    collect_unbounded_quantifiers(&clause.body, &f.name, &mut warnings);
                }
            }
            Decl::Extern(e) => {
                for clause in &e.clauses {
                    collect_unbounded_quantifiers(&clause.body, &e.name, &mut warnings);
                }
            }
            Decl::Service(s) => {
                for item in &s.items {
                    let (name, clauses) = match item {
                        ServiceItem::Operation { name, clauses } => (name, clauses),
                        ServiceItem::Query { name, clauses } => (name, clauses),
                        _ => continue,
                    };
                    let ctx = format!("{}::{}", s.name, name);
                    for clause in clauses {
                        collect_unbounded_quantifiers(&clause.body, &ctx, &mut warnings);
                    }
                }
            }
            _ => {}
        }
    }
    warnings
}

/// Recursively walk an expression looking for forall/exists with infinite domains.
fn collect_unbounded_quantifiers(
    expr: &Expr,
    context: &str,
    warnings: &mut Vec<UnboundedQuantifierWarning>,
) {
    match expr {
        Expr::Forall { var, domain, body } | Expr::Exists { var, domain, body } => {
            if let Some(reason) = check_infinite_domain(domain) {
                let kind = if matches!(expr, Expr::Forall { .. }) {
                    "forall"
                } else {
                    "exists"
                };
                warnings.push(UnboundedQuantifierWarning {
                    context: context.to_string(),
                    var: var.clone(),
                    domain_desc: format!("{kind} {var} in <{reason}>"),
                    reason: "quantifier ranges over infinite domain; \
                         use a bounded collection or range (e.g., 0..n) instead"
                        .to_string(),
                });
            }
            // Check nested quantifiers in body
            collect_unbounded_quantifiers(body, context, warnings);
            // Check domain sub-expressions too
            collect_unbounded_quantifiers(domain, context, warnings);
        }
        // Recurse into sub-expressions
        Expr::BinOp { lhs, rhs, .. } => {
            collect_unbounded_quantifiers(lhs, context, warnings);
            collect_unbounded_quantifiers(rhs, context, warnings);
        }
        Expr::UnaryOp { expr: e, .. }
        | Expr::Old(e)
        | Expr::Paren(e)
        | Expr::Ghost(e)
        | Expr::Field(e, _) => {
            collect_unbounded_quantifiers(e, context, warnings);
        }
        Expr::Call { func, args } => {
            collect_unbounded_quantifiers(func, context, warnings);
            for arg in args {
                collect_unbounded_quantifiers(arg, context, warnings);
            }
        }
        Expr::MethodCall { receiver, args, .. } => {
            collect_unbounded_quantifiers(receiver, context, warnings);
            for arg in args {
                collect_unbounded_quantifiers(arg, context, warnings);
            }
        }
        Expr::Index { expr: e, index } => {
            collect_unbounded_quantifiers(e, context, warnings);
            collect_unbounded_quantifiers(index, context, warnings);
        }
        Expr::If {
            cond,
            then_branch,
            else_branch,
        } => {
            collect_unbounded_quantifiers(cond, context, warnings);
            collect_unbounded_quantifiers(then_branch, context, warnings);
            if let Some(eb) = else_branch {
                collect_unbounded_quantifiers(eb, context, warnings);
            }
        }
        Expr::Let { value, body, .. } => {
            collect_unbounded_quantifiers(value, context, warnings);
            collect_unbounded_quantifiers(body, context, warnings);
        }
        Expr::Match { scrutinee, arms } => {
            collect_unbounded_quantifiers(scrutinee, context, warnings);
            for arm in arms {
                collect_unbounded_quantifiers(&arm.body, context, warnings);
            }
        }
        Expr::List(items) | Expr::Tuple(items) | Expr::Block(items) => {
            for item in items {
                collect_unbounded_quantifiers(item, context, warnings);
            }
        }
        Expr::Cast { expr: e, .. } => {
            collect_unbounded_quantifiers(e, context, warnings);
        }
        Expr::Apply { args, .. } => {
            for arg in args {
                collect_unbounded_quantifiers(arg, context, warnings);
            }
        }
        Expr::Raw(tokens) => {
            // Check for raw quantifier patterns: forall/exists VAR in DOMAIN : BODY
            check_raw_quantifier_bounds(tokens, context, warnings);
        }
        // Leaf nodes
        Expr::Literal(_) | Expr::Ident(_) => {}
    }
}

/// Check if a domain expression represents an infinite/unbounded type.
/// Returns Some(description) if infinite, None if bounded.
fn check_infinite_domain(domain: &Expr) -> Option<String> {
    match domain {
        Expr::Ident(name) => {
            if INFINITE_TYPE_NAMES.contains(&name.as_str()) {
                Some(name.clone())
            } else {
                None
            }
        }
        Expr::Raw(tokens) if tokens.len() == 1 => {
            if INFINITE_TYPE_NAMES.contains(&tokens[0].as_str()) {
                Some(tokens[0].clone())
            } else {
                None
            }
        }
        _ => None,
    }
}

/// Check raw token sequences for quantifiers with infinite domains.
fn check_raw_quantifier_bounds(
    tokens: &[String],
    context: &str,
    warnings: &mut Vec<UnboundedQuantifierWarning>,
) {
    let mut i = 0;
    while i + 4 < tokens.len() {
        let kind = tokens[i].as_str();
        if matches!(kind, "forall" | "exists")
            && tokens.get(i + 2).map(|s| s.as_str()) == Some("in")
        {
            // tokens[i+1] = var, tokens[i+3..colon] = domain
            let var = tokens[i + 1].clone();
            let domain_start = i + 3;
            // Find colon separator
            let colon_pos = tokens[domain_start..]
                .iter()
                .position(|t| t == ":")
                .map(|p| domain_start + p);
            let domain_end = colon_pos.unwrap_or(tokens.len());
            let domain_tokens = &tokens[domain_start..domain_end];
            if domain_tokens.len() == 1 && INFINITE_TYPE_NAMES.contains(&domain_tokens[0].as_str())
            {
                warnings.push(UnboundedQuantifierWarning {
                    context: context.to_string(),
                    var,
                    domain_desc: format!("{kind} over {}", domain_tokens[0]),
                    reason: format!(
                        "quantifier ranges over infinite domain `{}`; \
                         use a bounded collection or range (e.g., 0..n) instead",
                        domain_tokens[0]
                    ),
                });
            }
            i = domain_end + 1;
        } else {
            i += 1;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use assura_parser::ast::{BinOp, Expr, Literal};

    // ---- check_infinite_domain ----

    #[test]
    fn infinite_domain_int() {
        let e = Expr::Ident("Int".into());
        assert_eq!(check_infinite_domain(&e), Some("Int".into()));
    }

    #[test]
    fn infinite_domain_float() {
        let e = Expr::Ident("Float".into());
        assert_eq!(check_infinite_domain(&e), Some("Float".into()));
    }

    #[test]
    fn infinite_domain_string() {
        let e = Expr::Ident("String".into());
        assert_eq!(check_infinite_domain(&e), Some("String".into()));
    }

    #[test]
    fn finite_domain_custom_type() {
        let e = Expr::Ident("MyList".into());
        assert_eq!(check_infinite_domain(&e), None);
    }

    #[test]
    fn infinite_domain_raw_single_token() {
        let e = Expr::Raw(vec!["Nat".into()]);
        assert_eq!(check_infinite_domain(&e), Some("Nat".into()));
    }

    #[test]
    fn finite_domain_raw_multi_token() {
        let e = Expr::Raw(vec!["0".into(), "..".into(), "100".into()]);
        assert_eq!(check_infinite_domain(&e), None);
    }

    #[test]
    fn finite_domain_binop() {
        let e = Expr::BinOp {
            lhs: Box::new(Expr::Literal(Literal::Int("0".into()))),
            op: BinOp::Lt,
            rhs: Box::new(Expr::Literal(Literal::Int("100".into()))),
        };
        assert_eq!(check_infinite_domain(&e), None);
    }

    // ---- collect_unbounded_quantifiers ----

    #[test]
    fn forall_over_int_produces_warning() {
        let expr = Expr::Forall {
            var: "x".into(),
            domain: Box::new(Expr::Ident("Int".into())),
            body: Box::new(Expr::Literal(Literal::Bool(true))),
        };
        let mut warnings = Vec::new();
        collect_unbounded_quantifiers(&expr, "TestContract", &mut warnings);
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].var, "x");
        assert!(warnings[0].domain_desc.contains("forall"));
    }

    #[test]
    fn exists_over_nat_produces_warning() {
        let expr = Expr::Exists {
            var: "n".into(),
            domain: Box::new(Expr::Ident("Nat".into())),
            body: Box::new(Expr::Literal(Literal::Bool(true))),
        };
        let mut warnings = Vec::new();
        collect_unbounded_quantifiers(&expr, "TestFn", &mut warnings);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].domain_desc.contains("exists"));
    }

    #[test]
    fn forall_over_custom_type_no_warning() {
        let expr = Expr::Forall {
            var: "item".into(),
            domain: Box::new(Expr::Ident("items".into())),
            body: Box::new(Expr::Literal(Literal::Bool(true))),
        };
        let mut warnings = Vec::new();
        collect_unbounded_quantifiers(&expr, "TestContract", &mut warnings);
        assert!(warnings.is_empty());
    }

    #[test]
    fn nested_quantifier_both_warned() {
        let inner = Expr::Forall {
            var: "y".into(),
            domain: Box::new(Expr::Ident("Float".into())),
            body: Box::new(Expr::Literal(Literal::Bool(true))),
        };
        let outer = Expr::Forall {
            var: "x".into(),
            domain: Box::new(Expr::Ident("Int".into())),
            body: Box::new(inner),
        };
        let mut warnings = Vec::new();
        collect_unbounded_quantifiers(&outer, "Nested", &mut warnings);
        assert_eq!(warnings.len(), 2);
    }

    #[test]
    fn literal_no_warning() {
        let expr = Expr::Literal(Literal::Bool(true));
        let mut warnings = Vec::new();
        collect_unbounded_quantifiers(&expr, "ctx", &mut warnings);
        assert!(warnings.is_empty());
    }

    #[test]
    fn binop_recurses() {
        let expr = Expr::BinOp {
            lhs: Box::new(Expr::Forall {
                var: "x".into(),
                domain: Box::new(Expr::Ident("Int".into())),
                body: Box::new(Expr::Literal(Literal::Bool(true))),
            }),
            op: BinOp::And,
            rhs: Box::new(Expr::Literal(Literal::Bool(true))),
        };
        let mut warnings = Vec::new();
        collect_unbounded_quantifiers(&expr, "ctx", &mut warnings);
        assert_eq!(warnings.len(), 1);
    }

    // ---- check_raw_quantifier_bounds ----

    #[test]
    fn raw_forall_over_int_warns() {
        let tokens: Vec<String> = vec!["forall", "x", "in", "Int", ":", "x", ">", "0"]
            .into_iter()
            .map(String::from)
            .collect();
        let mut warnings = Vec::new();
        check_raw_quantifier_bounds(&tokens, "Raw", &mut warnings);
        assert_eq!(warnings.len(), 1);
        assert_eq!(warnings[0].var, "x");
    }

    #[test]
    fn raw_exists_over_string_warns() {
        let tokens: Vec<String> = vec!["exists", "s", "in", "String", ":", "true"]
            .into_iter()
            .map(String::from)
            .collect();
        let mut warnings = Vec::new();
        check_raw_quantifier_bounds(&tokens, "Raw", &mut warnings);
        assert_eq!(warnings.len(), 1);
    }

    #[test]
    fn raw_forall_over_list_no_warning() {
        let tokens: Vec<String> = vec!["forall", "x", "in", "items", ":", "x", ">", "0"]
            .into_iter()
            .map(String::from)
            .collect();
        let mut warnings = Vec::new();
        check_raw_quantifier_bounds(&tokens, "Raw", &mut warnings);
        assert!(warnings.is_empty());
    }

    #[test]
    fn raw_empty_tokens_no_warning() {
        let mut warnings = Vec::new();
        check_raw_quantifier_bounds(&[], "Raw", &mut warnings);
        assert!(warnings.is_empty());
    }

    // ---- UnboundedQuantifierWarning ----

    #[test]
    fn warning_fields() {
        let w = UnboundedQuantifierWarning {
            context: "MyContract".into(),
            var: "x".into(),
            domain_desc: "forall x in Int".into(),
            reason: "infinite domain".into(),
        };
        assert_eq!(w.context, "MyContract");
        assert_eq!(w.var, "x");
    }
}
